---
title: "biomass"
author: "Millie Chapman"
date: "2/25/2021"
output: github_document
---

```{r}
library(tidyverse)
library(sf)
library(ungeviz)
```

```{r}
abg_easement_uncertainty <- read_csv("../data/GEE/carbon/easement_abgcarbon_uncertainty.csv") %>%
  dplyr::select(agb_uncertainty_count, agb_uncertainty_sum) %>%
  dplyr::mutate(SE = agb_uncertainty_sum/agb_uncertainty_count) %>%
  select(agb_uncertainty_count,agb_uncertainty_sum, SE)

bg_easement_uncertainty <- read_csv("../data/GEE/carbon/easement_bgcarbon_uncertainty.csv")%>%
  dplyr::select(bgb_uncertainty_count, bgb_uncertainty_sum) %>%
  dplyr::mutate(SE = bgb_uncertainty_sum/bgb_uncertainty_count) %>%   select(bgb_uncertainty_count,bgb_uncertainty_sum, SE)


agb_fee_uncertainty <- read_csv("../data/GEE/carbon/fee_abgcarbon_uncertainty.csv")%>%
  dplyr::select(agb_uncertainty_count, agb_uncertainty_sum) %>%
  dplyr::mutate(SE = agb_uncertainty_sum/agb_uncertainty_count) %>%
    select(agb_uncertainty_count,agb_uncertainty_sum, SE)



bg_fee_uncertainty <- read_csv("../data/GEE/carbon/fee_bgcarbon_uncertainty.csv")%>%
  dplyr::select(bgb_uncertainty_count, bgb_uncertainty_sum) %>%
  dplyr::mutate(SE = bgb_uncertainty_sum/bgb_uncertainty_count) %>%
    select(bgb_uncertainty_count,bgb_uncertainty_sum, SE)
```

```{r}
abg_easement <- read_csv("../data/GEE/carbon/easement_abgcarbon2.csv") %>%
  bind_cols(abg_easement_uncertainty)

bg_easement <- read_csv("../data/GEE/carbon/easement_bgcarbon2.csv") %>%
  bind_cols(bg_easement_uncertainty)
  
agb_fee <- read_csv("../data/GEE/carbon/fee_abgcarbon2.csv") %>%
  bind_cols(agb_fee_uncertainty)

bg_fee <- read_csv("../data/GEE/carbon/fee_bgcarbon2.csv")%>%
  bind_cols(bg_fee_uncertainty)
```


```{r}
bg_easement_table <- bg_easement %>%
  filter(GAP_Sts == 2 |GAP_Sts == 1) %>%
  dplyr::mutate(total_area = sum(bgb_count),
                type = "easements",
                carbon = "below ground\ncarbon") %>%
  select(total_area,type, carbon, bgb_sum, bgb_uncertainty_sum) %>%
  remove_missing() %>%
  #mutate(biomass_mean = bgb_sum/total_area) %>%
  group_by(carbon, type) %>%
  summarise(biomass_mean = sum(bgb_sum/total_area),
            SE = sum(bgb_uncertainty_sum/total_area)) %>% 
  unique()

easement <- abg_easement %>%
  filter(GAP_Sts == 2 |GAP_Sts == 1) %>%
  dplyr::mutate(total_area = sum(agb_count),
                type = "easements",
                carbon = "above ground\ncarbon") %>%
  select(total_area,type, carbon, agb_sum, agb_uncertainty_sum) %>%
  #mutate(biomass_mean = bgb_sum/total_area) %>%
  group_by(carbon, type) %>%
  summarise(biomass_mean = sum(agb_sum/total_area),
            SE = sum(agb_uncertainty_sum/total_area)) %>%  unique() %>%
  bind_rows(bg_easement_table) 
```

```{r}
pa_bg <- bg_fee %>%
  filter(GAP_Sts == 2 |GAP_Sts == 1) %>%
  dplyr::mutate(total_area = sum(bgb_count),
                type = "protected areas",
                carbon = "below ground\ncarbon") %>%
  select(total_area,type, carbon, bgb_sum, bgb_uncertainty_sum) %>%
  #mutate(biomass_mean = bgb_sum/total_area) %>%
  group_by(carbon, type) %>%
  summarise(biomass_mean = sum(bgb_sum/total_area),
            SE = sum(bgb_uncertainty_sum/total_area)) %>% 
  unique()
  

pa <- agb_fee %>%
  filter(GAP_Sts == 2 |GAP_Sts == 1) %>%
  dplyr::mutate(total_area = sum(agb_count),
                type = "protected areas",
                carbon = "above ground\ncarbon") %>%
  select(total_area,type, carbon, agb_sum,agb_uncertainty_sum ) %>%
  #mutate(biomass_mean = bgb_sum/total_area) %>%
  group_by(carbon, type) %>%
  summarise(biomass_mean = sum(agb_sum/total_area),
            SE = sum(agb_uncertainty_sum/total_area)) %>% ungroup() %>%
  unique() %>% bind_rows(pa_bg)
```

```{r}
carbon <- pa %>%
  bind_rows(easement)
```

```{r}
bg_background <- read_csv("../data/GEE/carbon/us_bgcarbon_states.csv")
abg_background <- read_csv("../data/GEE/carbon/us_abgcarbon_states.csv")
```

```{r}
bg_background <- bg_background %>%
  dplyr::mutate(total_area = sum(bgb_count),
                type = "background",
                carbon = "below ground\ncarbon") %>%
  select(total_area,type, carbon, bgb_sum) %>%
  #mutate(biomass_mean = bgb_sum/total_area) %>%
  group_by(carbon, type) %>%
  summarise(biomass_mean = sum(bgb_sum, na.rm = TRUE)/(total_area)) %>% 
  unique()

background <- abg_background %>%
  dplyr::mutate(total_area = sum(agb_count),
                type = "background",
                carbon = "above ground\ncarbon") %>%
  select(total_area,type, carbon, agb_sum) %>%
  #mutate(biomass_mean = bgb_sum/total_area) %>%
  group_by(carbon, type) %>%
  summarise(biomass_mean = sum(agb_sum, na.rm = TRUE)/(total_area)) %>%  unique() %>%
  bind_rows(bg_background) 
```

```{r carbon_fig, fig.height=4, fig.width=3.5,dpi=500}
carbon %>%
  ggplot(aes(x = carbon, y = biomass_mean, fill = type)) +
  geom_bar(stat = "identity", width=0.65,position=position_dodge(width=0.8)) +
 # geom_errorbar(aes(x = carbon, ymin = biomass_mean-SE, ymax = biomass_mean+SE, group = type), position = position_dodge(width=0.8), width = 0.25) +
  scale_fill_manual(values=c("#0072B2","#E69F00")) +
 # geom_hpline(data = background, aes(x=carbon, y =biomass_mean), stat = "identity", height = 0.4, lwd = .75) +
 # geom_point(background, mapping = aes(x = carbon, y= biomass_mean), pch = 19)+
  theme_minimal() +
  labs(y = "mean carbon density (Mg/ha)") +
  theme(axis.title.x =element_blank()) +
  theme(legend.title = element_blank()) + #coord_flip() +
  theme(legend.position = "none") +
   theme(axis.text=element_text(size=10),
        axis.title=element_text(size=10),
        panel.border = element_rect(colour = "black", fill=NA),
        legend.box.background = element_rect(colour = "black"),
        legend.text = element_text(size = 8)) +
  guides(shape = guide_legend(override.aes = list(size = 5))) 
```

```{r}
fee_exp <- st_read("../data/GEE/feeexpnum.shp") %>%
  filter(GAP_Sts == 1 | GAP_Sts == 2) %>%
  mutate(area = st_area(geometry)) %>%
  mutate(PA_CE = "protected area") %>%
  group_by(PA_CE) %>%
  mutate(total_area = sum(area)) %>% ungroup()

fee_exp <- as_tibble(fee_exp) %>%
  select(Date_Est, GAP_Sts, area,State_Nm,  num, total_area, PA_CE) 
```


```{r}
total_carbon_easements <- read_csv("../data/GEE/carbon/easement_carbon_sum.csv") %>%
  mutate(PA_CE = "easements") %>%
  filter(GAP_Sts == 1 | GAP_Sts == 2) %>%
  group_by(PA_CE) %>%
  summarise(agb = sum(agb),
            bgb = sum(bgb))


total_carbon_pa <- read_csv("../data/GEE/carbon/fee_carbon_sum.csv") %>%
  select(agb:num) %>%
  left_join(fee_exp, by = "num") %>%
  filter(GAP_Sts == 1 | GAP_Sts == 2) %>%
  group_by(PA_CE) %>%
  summarise(agb = sum(agb),
            bgb = sum(bgb))
```

```{r}
total_carbon_pa %>%
  bind_rows(total_carbon_easements) %>%
  pivot_longer(-PA_CE)
```

```{r}
total_carbon_pa %>%
  bind_rows(total_carbon_easements) %>%
  pivot_longer(-PA_CE) %>%
  mutate(value = value/10^9) %>%
  ggplot(aes(x= PA_CE, y = value, fill = name)) + 
  geom_bar(stat = "identity") 
```

