---
title: "climate-analysis"
author: "Millie Chapman"
date: "3/14/2021"
output: github_document
---

```{r}
library(tidyverse)
library(raster)
library(sf)
library(rgdal)
```

GF

```{r}
#generate a list of input rasters ("grids")
#pattern = "*.tif$" - filters for main raster files only and skips any associated files (e.g. world files)
grids <- list.files("../data/climate-distributions/SpeciesProjections/Future/gf85bi70/Mammals",pattern="*.tif$")

#create a raster stack from the input raster files 

#run the sum function on the raster stack - i.e. add (non-cumulatively) the rasters together
if (!file.exists("../data/climate-distributions/SpeciesProjections/future_mammals_gf.tif")) {
  s <- raster::stack(paste0("../data/climate-distributions/SpeciesProjections/Future/gf85bi70/Mammals/", grids))
  r <- calc(s, sum, na.rm = TRUE)
  writeRaster(r, "../data/climate-distributions/SpeciesProjections/future_mammals_gf.tif")
}

#generate a list of input rasters ("grids")
#pattern = "*.tif$" - filters for main raster files only and skips any associated files (e.g. world files)
grids <- list.files("../data/climate-distributions/SpeciesProjections/Future/gf85bi70/Birds/",pattern="*.tif$")

#create a raster stack from the input raster files 
#run the sum function on the raster stack - i.e. add (non-cumulatively) the rasters together
if (!file.exists("../data/climate-distributions/SpeciesProjections/future_birds_gf.tif")) {
  s <- raster::stack(paste0("../data/climate-distributions/SpeciesProjections/Future/gf85bi70/Birds/", grids))
  r <- calc(s, sum, na.rm = TRUE)
  writeRaster(r, "../data/climate-distributions/SpeciesProjections/future_birds_gf.tif")
}

#generate a list of input rasters ("grids")
#pattern = "*.tif$" - filters for main raster files only and skips any associated files (e.g. world files)
grids <- list.files("../data/climate-distributions/SpeciesProjections/Future/gf85bi70/Amphibians/",pattern="*.tif$")

if (!file.exists("../data/climate-distributions/SpeciesProjections/future_amphibians_gf.tif")) {
  s <- raster::stack(paste0("../data/climate-distributions/SpeciesProjections/Future/gf85bi70/Amphibians/", grids))
  r <- calc(s, sum, na.rm = TRUE)
  writeRaster(r, "../data/climate-distributions/SpeciesProjections/future_amphibians_gf.tif")
}

#generate a list of input rasters ("grids")
#pattern = "*.tif$" - filters for main raster files only and skips any associated files (e.g. world files)
grids <- list.files("../data/climate-distributions/SpeciesProjections/Future/gf85bi70/Reptiles/",pattern="*.tif$")

if (!file.exists("../data/climate-distributions/SpeciesProjections/future_reptiles_gf.tif")) {
  s <- raster::stack(paste0("../data/climate-distributions/SpeciesProjections/Future/gf85bi70/Reptiles/", grids))
  r <- calc(s, sum, na.rm = TRUE)
  writeRaster(r, "../data/climate-distributions/SpeciesProjections/future_reptiles_gf.tif")
}
```


```{r}
#generate a list of input rasters ("grids")
#pattern = "*.tif$" - filters for main raster files only and skips any associated files (e.g. world files)
grids <- list.files("../data/climate-distributions/SpeciesProjections/Future/in85bi70/Mammals/",pattern="*.tif$")

#create a raster stack from the input raster files 

#run the sum function on the raster stack - i.e. add (non-cumulatively) the rasters together
if (!file.exists("../data/climate-distributions/SpeciesProjections/future_mammals_in.tif")) {
  s <- raster::stack(paste0("../data/climate-distributions/SpeciesProjections/Future/in85bi70/Mammals/", grids))
  r <- calc(s, sum, na.rm = TRUE)
  writeRaster(r, "../data/climate-distributions/SpeciesProjections/future_mammals_in.tif")
}

#generate a list of input rasters ("grids")
#pattern = "*.tif$" - filters for main raster files only and skips any associated files (e.g. world files)
grids <- list.files("../data/climate-distributions/SpeciesProjections/Future/in85bi70/Birds/",pattern="*.tif$")

#create a raster stack from the input raster files 
#run the sum function on the raster stack - i.e. add (non-cumulatively) the rasters together
if (!file.exists("../data/climate-distributions/SpeciesProjections/future_birds_in.tif")) {
  s <- raster::stack(paste0("../data/climate-distributions/SpeciesProjections/Future/in85bi70/Birds/", grids))
  r <- calc(s, sum, na.rm = TRUE)
  writeRaster(r, "../data/climate-distributions/SpeciesProjections/future_birds_in.tif")
}

#generate a list of input rasters ("grids")
#pattern = "*.tif$" - filters for main raster files only and skips any associated files (e.g. world files)
grids <- list.files("../data/climate-distributions/SpeciesProjections/Future/in85bi70/Amphibians/",pattern="*.tif$")

if (!file.exists("../data/climate-distributions/SpeciesProjections/future_amphibians_in.tif")) {
  s <- raster::stack(paste0("../data/climate-distributions/SpeciesProjections/Future/in85bi70/Amphibians/", grids))
  r <- calc(s, sum, na.rm = TRUE)
  writeRaster(r, "../data/climate-distributions/SpeciesProjections/future_amphibians_in.tif")
}

#generate a list of input rasters ("grids")
#pattern = "*.tif$" - filters for main raster files only and skips any associated files (e.g. world files)
grids <- list.files("../data/climate-distributions/SpeciesProjections/Future/in85bi70/Reptiles/",pattern="*.tif$")

if (!file.exists("../data/climate-distributions/SpeciesProjections/future_reptiles_in.tif")) {
  s <- raster::stack(paste0("../data/climate-distributions/SpeciesProjections/Future/in85bi70/Reptiles/", grids))
  r <- calc(s, sum, na.rm = TRUE)
  writeRaster(r, "../data/climate-distributions/SpeciesProjections/future_reptiles_in.tif")
}
```

```{r}
#generate a list of input rasters ("grids")
#pattern = "*.tif$" - filters for main raster files only and skips any associated files (e.g. world files)
grids <- list.files("../data/climate-distributions/SpeciesProjections/Future/mc85bi70/Mammals/",pattern="*.tif$")

#create a raster stack from the input raster files 

#run the sum function on the raster stack - i.e. add (non-cumulatively) the rasters together
if (!file.exists("../data/climate-distributions/SpeciesProjections/future_mammals_mc.tif")) {
  s <- raster::stack(paste0("../data/climate-distributions/SpeciesProjections/Future/mc85bi70/Mammals/", grids))
  r <- calc(s, sum, na.rm = TRUE)
  writeRaster(r, "../data/climate-distributions/SpeciesProjections/future_mammals_mc.tif")
}

#generate a list of input rasters ("grids")
#pattern = "*.tif$" - filters for main raster files only and skips any associated files (e.g. world files)
grids <- list.files("../data/climate-distributions/SpeciesProjections/Future/mc85bi70/Birds/",pattern="*.tif$")

#create a raster stack from the input raster files 
#run the sum function on the raster stack - i.e. add (non-cumulatively) the rasters together
if (!file.exists("../data/climate-distributions/SpeciesProjections/future_birds_mc.tif")) {
  s <- raster::stack(paste0("../data/climate-distributions/SpeciesProjections/Future/mc85bi70/Birds/", grids))
  r <- calc(s, sum, na.rm = TRUE)
  writeRaster(r, "../data/climate-distributions/SpeciesProjections/future_birds_mc.tif")
}

#generate a list of input rasters ("grids")
#pattern = "*.tif$" - filters for main raster files only and skips any associated files (e.g. world files)
grids <- list.files("../data/climate-distributions/SpeciesProjections/Future/mc85bi70/Amphibians/",pattern="*.tif$")

if (!file.exists("../data/climate-distributions/SpeciesProjections/future_amphibians_mc.tif")) {
  s <- raster::stack(paste0("../data/climate-distributions/SpeciesProjections/Future/mc85bi70/Amphibians/", grids))
  r <- calc(s, sum, na.rm = TRUE)
  writeRaster(r, "../data/climate-distributions/SpeciesProjections/future_amphibians_mc.tif")
}

#generate a list of input rasters ("grids")
#pattern = "*.tif$" - filters for main raster files only and skips any associated files (e.g. world files)
grids <- list.files("../data/climate-distributions/SpeciesProjections/Future/mc85bi70/Reptiles/",pattern="*.tif$")

if (!file.exists("../data/climate-distributions/SpeciesProjections/future_reptiles_mc.tif")) {
  s <- raster::stack(paste0("../data/climate-distributions/SpeciesProjections/Future/mc85bi70/Reptiles/", grids))
  r <- calc(s, sum, na.rm = TRUE)
  writeRaster(r, "../data/climate-distributions/SpeciesProjections/future_reptiles_mc.tif")
}
```


mammals
```{r}
mc <- raster("../data/climate-distributions/SpeciesProjections/future_mammals_mc.tif")
inp <- raster("../data/climate-distributions/SpeciesProjections/future_mammals_in.tif")
gf <- raster("../data/climate-distributions/SpeciesProjections/future_mammals_gf.tif")

raster <- stack(mc,inp,gf)
raster <- calc(raster, sum, na.rm = TRUE)
rasterm <- raster/3

writeRaster(rasterm, "../data/climate-distributions/SpeciesProjections/future_mammals_ave.tif", append = FALSE)
```

birds
```{r}
mc <- raster("../data/climate-distributions/SpeciesProjections/future_birds_mc.tif")
inp <- raster("../data/climate-distributions/SpeciesProjections/future_birds_in.tif")
gf <- raster("../data/climate-distributions/SpeciesProjections/future_birds_gf.tif")

raster <- stack(mc,inp,gf)
raster <- calc(raster, sum, na.rm = TRUE)
rasterb <- raster/3

writeRaster(rasterb, "../data/climate-distributions/SpeciesProjections/future_birds_ave.tif", append = FALSE)
```

reptiles

```{r}
mc <- raster("../data/climate-distributions/SpeciesProjections/future_reptiles_mc.tif")
inp <- raster("../data/climate-distributions/SpeciesProjections/future_reptiles_in.tif")
gf <- raster("../data/climate-distributions/SpeciesProjections/future_reptiles_gf.tif")

raster <- stack(mc,inp,gf)
raster <- calc(raster, sum, na.rm = TRUE)
rasterr <- raster/3

writeRaster(rasterr, "../data/climate-distributions/SpeciesProjections/future_reptiles_ave.tif", append = FALSE)
```


amphibians
```{r}
mc <- raster("../data/climate-distributions/SpeciesProjections/future_amphibians_mc.tif")
inp <- raster("../data/climate-distributions/SpeciesProjections/future_amphibians_in.tif")
gf <- raster("../data/climate-distributions/SpeciesProjections/future_amphibians_gf.tif")

raster <- stack(mc,inp,gf)
raster <- calc(raster, sum, na.rm = TRUE)
rastera <- raster/3

writeRaster(rastera, "../data/climate-distributions/SpeciesProjections/future_amphibians_ave.tif", append = FALSE)
```






```{r}
easement <- st_read("../data/PADUS2_0_Shapefiles/PADUS2_0Easement.shp")
fee <- st_read("../data/PADUS2_0_Shapefiles/PADUS2_0Fee.shp")
background <- st_read("../data/gadm36_USA_shp/gadm36_USA_1.shp")
background <- st_transform(background, st_crs(easement))
crs_sf <- st_crs(easement)
```

```{r}
reptile_richness <- raster("../data/climate-distributions/SpeciesProjections/future_reptiles_gf.tif")
mammal_richness <- raster("../data/climate-distributions/SpeciesProjections/future_mammals_gf.tif")
bird_richness <- raster("../data/climate-distributions/SpeciesProjections/future_birds_gf.tif")
amphibian_richness <- raster("../data/climate-distributions/SpeciesProjections/future_amphibians_gf.tif")
plant_richness <- raster("../data/climate-distributions/SpeciesProjections/future_plants_gf.tif")
```

```{r, warning=FALSE,cache=TRUE}
fee <- fee %>% 
  dplyr::filter(SHAPE_Area > 1)

fee <- fee %>%
  dplyr::mutate(valid = st_is_valid(fee)) %>%
  dplyr::filter(valid == "TRUE")

fee_exp <- fee %>% select(Date_Est, GAP_Sts, d_State_Nm, State_Nm, Category, Mang_Type)
```

```{r}
st_write(fee_exp, "../data/GEE/fee_valid.shp", append = TRUE)
```


```{r}
NAvalue(mammal_richness) <- 0
NAvalue(reptile_richness) <- 0
NAvalue(amphibian_richness) <- 0
NAvalue(bird_richness) <- 0
NAvalue(plant_richness) <- 0
```

```{r}
plot(bird_richness)
```

```{r, warning=FALSE}
easement1 <- easement %>% 
  dplyr::filter(GAP_Sts == "1") %>%
  st_transform(crs(mammal_richness))
```

```{r, warning=FALSE}
easement2 <- easement %>% 
  dplyr::filter(GAP_Sts == "2") %>%
  st_transform(crs(mammal_richness))
```

```{r}
fee <- fee %>%
  st_transform(crs(mammal_richness))
```


```{r warning=FALSE}
fee_richness <- fee  %>%
  dplyr::mutate(mammal_richness = raster::extract(mammal_richness, fee, fun=mean, na.rm = TRUE),
                reptile_richness = raster::extract(reptile_richness, fee, fun=mean, na.rm = TRUE),
                amphibian_richness = raster::extract(amphibian_richness, fee, fun=mean, na.rm = TRUE),
                bird_richness = raster::extract(bird_richness, fee, fun=mean, na.rm = TRUE),
                plant_richness = raster::extract(plant_richness, fee, fun=mean, na.rm = TRUE))
```

```{r}
st_write(fee_richness, "../data/output/fee_richness_future.shp",append = FALSE)
```

```{r}
raster::beginCluster()
easement_richness1 <- easement1 %>%
  dplyr::mutate(mammal_richness = raster::extract(mammal_richness, easement1, fun=mean, na.rm = TRUE),
                reptile_richness = raster::extract(reptile_richness, easement1, fun=mean, na.rm = TRUE),
                amphibian_richness = raster::extract(amphibian_richness, easement1, fun=mean, na.rm = TRUE),
                bird_richness = raster::extract(bird_richness, easement1, fun=mean, na.rm = TRUE),
                plant_richness = raster::extract(plant_richness, fee, fun=mean, na.rm = TRUE))
endCluster()
```

```{r}
st_write(easement_richness1, "../data/output/easement_richness1_future.shp", append = FALSE)
```

```{r}
raster::beginCluster()
easement_richness2 <- easement2 %>%
  dplyr::mutate(mammal_richness = raster::extract(mammal_richness, easement2, fun=mean, na.rm = TRUE),
                reptile_richness = raster::extract(reptile_richness, easement2, fun=mean, na.rm = TRUE),
                amphibian_richness = raster::extract(amphibian_richness, easement2, fun=mean, na.rm = TRUE),
                bird_richness = raster::extract(bird_richness, easement2, fun=mean, na.rm = TRUE),
                plant_richness = raster::extract(plant_richness, fee, fun=mean, na.rm = TRUE))
```

```{r}
st_write(easement_richness2, "../data/output/easement_richness2_future.shp", append = FALSE)
```


```{r, warning=FALSE}
raster::beginCluster()
background_richness <- background %>%
  dplyr::mutate(mammal_richness = raster::extract(mammal_richness, background, fun=mean, na.rm = TRUE),
                reptile_richness = raster::extract(reptile_richness, background, fun=mean, na.rm = TRUE),
                amphibian_richness = raster::extract(amphibian_richness, background, fun=mean, na.rm = TRUE),
                fish_richness = raster::extract(bird_richness, background, fun=mean, na.rm = TRUE),
                plant_richness = raster::extract(plant_richness, fee, fun=mean, na.rm = TRUE))
endCluster()
```

```{r}
st_write(background_richness, "../data/output/background_richness_future.shp", append = FALSE)
```


```{r}
library(sf)
library(tidyverse)
library(ggplot2)
library(ungeviz)
```

```{r}
fee_richness <- st_read("../data/output/fee_richness_future.shp")
```

```{r}
easement_richness1 <- st_read("../data/output/easement_richness1_future.shp")
easement_richness2 <- st_read("../data/output/easement_richness2_future.shp")
easement_richness <- easement_richness1 %>%
  bind_rows(easement_richness2)
```

```{r}
background_richness <- st_read("../data/output/background_richness_future.shp")
```

area weight biodiversity 
```{r}
easement <- easement_richness %>%
  mutate(area = st_area(geometry)) %>%
  mutate(total_area = sum(area)) %>%
  mutate(perc_area = area/total_area) %>%
  mutate(reptiles = mean(rptl_rc, na.rm = TRUE)*perc_area,
         amphibians = mean(amphbn_, na.rm = TRUE)*perc_area,
         mammals= mean(mmml_rc, na.rm = TRUE)*perc_area,
         birds = mean(brd_rch, na.rm = TRUE)*perc_area,
         fish = mean(fsh_rch, na.rm = TRUE)*perc_area)

fee <- fee_richness %>%
  mutate(area = st_area(geometry)) %>%
  mutate(total_area = sum(area)) %>%
  mutate(perc_area = area/total_area) %>%
  mutate(reptiles = mean(rptl_rc, na.rm = TRUE)*perc_area,
         amphibians = mean(amphbn_, na.rm = TRUE)*perc_area,
         mammals= mean(mmml_rc, na.rm = TRUE)*perc_area,
         birds = mean(brd_rch, na.rm = TRUE)*perc_area,
         fish = mean(fsh_rch, na.rm = TRUE)*perc_area)
```

```{r}
dplyr::as_tibble(fee) %>%
  group_by(GAP_Sts) %>%
  count()
```

```{r}
richness_easement <- dplyr::as_tibble(easement) %>%
  dplyr::mutate(type = "easement",
                perc_area = area/total_area) %>%
  dplyr::group_by(type) %>%
  dplyr::summarize(reptiles = sum(reptiles, na.rm = TRUE),
            amphibians = sum(amphibians, na.rm = TRUE),
            mammals= sum(mammals, na.rm = TRUE),
            birds = sum(birds, na.rm = TRUE),
            fish = sum(fish, na.rm = TRUE))
  
richness_pa <- dplyr::as_tibble(fee) %>%
  mutate(type = "protected area") %>%
  #filter(GAP_Sts == "2") %>%
  group_by(type) %>%
  dplyr::summarize(reptiles = sum(reptiles, na.rm = TRUE),
            amphibians = sum(amphibians, na.rm = TRUE),
            mammals= sum(mammals, na.rm = TRUE),
            birds = sum(birds, na.rm = TRUE),
            fish = sum(fish, na.rm = TRUE))
```



```{r}
richness_all <- as_tibble(background_richness) %>%
  dplyr::mutate(type = NAME_0,
         reptiles = mean(rptl_rc, na.rm = TRUE),
         amphibians = mean(amphbn_, na.rm = TRUE),
         mammals= mean(mmml_rc, na.rm = TRUE),
         birds = mean(brd_rch, na.rm = TRUE),
         fish = mean(fsh_rch, na.rm = TRUE)) %>% 
  select(type, reptiles, amphibians, mammals, birds, fish)

richness_protected <-richness_pa %>%
  bind_rows(richness_easement) %>%
  tidyr::pivot_longer(reptiles:fish) 

richness_background <- richness_all %>%
  tidyr::pivot_longer(reptiles:fish)
```

```{r}
private_public_richness <- read_csv("../data/private_public_richness.csv")
```


```{r fig1b, fig.width=4, fig.height=5, dpi = 600}
ggplot() + 
  scale_fill_manual(values=c("#0072B2", "#E69F00")) +
  geom_bar(richness_protected, mapping = aes(x= name, y= as.numeric(value), fill = type),
                                  stat = "identity", width=0.65,
                                  position=position_dodge(width=0.8)) +
  geom_hpline(data = richness_background, aes(x=name, y =value), stat = "identity", height = 0.4, lwd = .9) +
  geom_point(richness_background, mapping = aes(x = name, y= value), pch = 19) +
  geom_point(private_public_richness, mapping = aes(x = name, y= as.numeric(value),  group = type), stat = "identity", position=position_dodge(width=0.8),  pch = 23, size = 2) +
  scale_color_manual(values=c("black", "black")) +
  theme_minimal() +
  theme(axis.title.y =element_blank()) +
  theme(axis.text.y = element_text(angle = 90,hjust=0.5)) +
  theme(legend.title = element_blank()) + coord_flip() +
  theme(legend.position = c(0.78, 0.89)) +
   theme(axis.text=element_text(size=8),
        axis.title=element_text(size=10),
        panel.border = element_rect(colour = "black", fill=NA),
        legend.box.background = element_rect(colour = "black"),
        legend.text = element_text(size = 8)) +
  guides(shape = guide_legend(override.aes = list(size = 5))) +
    labs(y = "mean species richness") 
 ## facet_grid(rows = vars(GAP_Sts))
```