---
title: "figures"
author: "Millie Chapman"
date: "2/25/2021"
output: github_document
---

```{r}
library(sf)
library(tidyverse)
library(ggplot2)
library(ungeviz)
```

```{r}
fee_richness <- st_read("../data/output/fee_richness.shp")
```

```{r}
easement_richness1 <- st_read("../data/output/easement_richness1.shp")
easement_richness2 <- st_read("../data/output/easement_richness2.shp")
easement_richness <- easement_richness1 %>%
  bind_rows(easement_richness2)
```

```{r}
background_richness <- st_read("../data/output/background_richness.shp")
```

area weight biodiversity 
```{r}
easement <- easement_richness %>%
  mutate(area = st_area(geometry)) %>%
  mutate(total_area = sum(area)) %>%
  mutate(perc_area = area/total_area) %>%
  mutate(reptiles = mean(rptl_rc, na.rm = TRUE)*perc_area,
         amphibians = mean(amphbn_, na.rm = TRUE)*perc_area,
         mammals= mean(mmml_rc, na.rm = TRUE)*perc_area,
         birds = mean(brd_rch, na.rm = TRUE)*perc_area,
         fish = mean(fsh_rch, na.rm = TRUE)*perc_area)

fee <- fee_richness %>%
  mutate(area = st_area(geometry)) %>%
  mutate(total_area = sum(area)) %>%
  mutate(perc_area = area/total_area) %>%
  mutate(reptiles = mean(rptl_rc, na.rm = TRUE)*perc_area,
         amphibians = mean(amphbn_, na.rm = TRUE)*perc_area,
         mammals= mean(mmml_rc, na.rm = TRUE)*perc_area,
         birds = mean(brd_rch, na.rm = TRUE)*perc_area,
         fish = mean(fsh_rch, na.rm = TRUE)*perc_area)
```

```{r}
dplyr::as_tibble(fee) %>%
  group_by(GAP_Sts) %>%
  count()
```

```{r}
richness_easement <- dplyr::as_tibble(easement) %>%
  dplyr::mutate(type = "easement",
                perc_area = area/total_area) %>%
  dplyr::group_by(type) %>%
  dplyr::summarize(reptiles = sum(reptiles, na.rm = TRUE),
            amphibians = sum(amphibians, na.rm = TRUE),
            mammals= sum(mammals, na.rm = TRUE),
            birds = sum(birds, na.rm = TRUE),
            fish = sum(fish, na.rm = TRUE),
            `aggregate \n richness` = reptiles+amphibians+mammals+birds+fish)
  
richness_pa <- dplyr::as_tibble(fee) %>%
  mutate(type = "protected area") %>%
  #filter(GAP_Sts == "2") %>%
  group_by(type) %>%
  dplyr::summarize(reptiles = sum(reptiles, na.rm = TRUE),
            amphibians = sum(amphibians, na.rm = TRUE),
            mammals= sum(mammals, na.rm = TRUE),
            birds = sum(birds, na.rm = TRUE),
            fish = sum(fish, na.rm = TRUE),
            `aggregate \n richness` = reptiles+amphibians+mammals+birds+fish)
```



```{r}
richness_all <- as_tibble(background_richness) %>%
  dplyr::mutate(type = NAME_0,
         reptiles = mean(rptl_rc, na.rm = TRUE),
         amphibians = mean(amphbn_, na.rm = TRUE),
         mammals= mean(mmml_rc, na.rm = TRUE),
         birds = mean(brd_rch, na.rm = TRUE),
         fish = mean(fsh_rch, na.rm = TRUE),
         `aggregate \n richness` = reptiles+amphibians+mammals+birds+fish) %>% 
  select(type, reptiles, amphibians, mammals, birds, fish, `aggregate \n richness`)

richness_protected <-richness_pa %>%
  bind_rows(richness_easement) %>%
  tidyr::pivot_longer(reptiles:`aggregate \n richness`) 

richness_background <- richness_all %>%
  tidyr::pivot_longer(reptiles:`aggregate \n richness`) %>%
  rename(background = "value") %>%
  select(-type)
```

```{r}
private_public_richness1 <- read_csv("../data/private_public_richness.csv") %>%
  left_join(richness_background) #%>%
   #mutate(richness = (as.numeric(value)- as.numeric(background))/as.numeric(background))

rows <- private_public_richness1 %>% 
  mutate(name = "aggregate \n richness") %>%
  group_by(type, name) %>%
  summarise(value = sum(value),
            background = sum(background)) %>% 
  ungroup()

private_public_richness<- private_public_richness1 %>%
  bind_rows(rows) %>%
  mutate(richness = (as.numeric(value)- as.numeric(background))/as.numeric(background)*100)
```

```{r}
richness_protected %>%
  left_join(richness_background) 
```


```{r fig1b, fig.width=4.5, fig.height=5, dpi = 600}
richness_protected %>%
  left_join(richness_background) %>%
  mutate(richness = (as.numeric(value)- as.numeric(background))/as.numeric(background)*100) %>%
  mutate(name = factor(name, levels = c("aggregate \n richness", "birds", "mammals", "fish", "amphibians", "reptiles"))) %>%
  mutate(arranged = ifelse(name == "aggregate \n richness", 1, 0)) %>%
  ggplot() + 
  scale_fill_manual(values=c("#0072B2", "#E69F00")) +
  geom_bar(mapping = aes(x= reorder(name, arranged), y= as.numeric(richness), fill = type),
                                  stat = "identity", width=0.65,
                                  position=position_dodge(width=0.8)) +
  geom_hline(yintercept=0, linetype="dashed") +
  #geom_point(richness_background, mapping = aes(x = name, y= value), pch = 19) +
  geom_point(private_public_richness, mapping = aes(x = name, y= as.numeric(richness),  group = type, color = type), stat = "identity", position=position_dodge(width=0.8),  pch = 18, size = 3) +
  scale_color_manual(values=c("#0072B2", "#E69F00")) +
  theme_minimal() +
  theme(axis.title.y =element_blank()) +
  theme(axis.text.y = element_text(angle = 90,hjust=0.5)) +
  theme(legend.title = element_blank()) + coord_flip() +
  theme(legend.position = "bottom") +
  ylim(-95,95) +
   theme(axis.text=element_text(size=8),
        axis.title=element_text(size=10),
        panel.border = element_rect(colour = "black", fill=NA),
        legend.box.background = element_rect(colour = "black"),
        legend.text = element_text(size = 8)) +
  guides(shape = guide_legend(override.aes = list(size = 5))) +
    labs(y = "% difference from background mean species richness") 
 ## facet_grid(rows = vars(GAP_Sts))
```

##Over time!

```{r}
easement_time <- as_tibble(easement_richness) %>%
  mutate(area = st_area(geometry)) %>%
  mutate(Accss_D = ifelse(Dat_Est < 2010 & Dat_Est > 2000,"2000-2010", 
                          ifelse(Dat_Est > 2010, "2011-2019", NA)),
         reptiles = rptl_rc,
         amphibians = amphbn_,
         mammals= mmml_rc,
         birds = brd_rch,
         fish = fsh_rch)%>%
  mutate(aggregated = reptiles + amphibians + mammals + birds + fish) %>%
  mutate(Accss_D = factor(Accss_D, levels = c("2000-2010","2011-2019"))) %>%
  select(Accss_D, reptiles:aggregated) %>%
  pivot_longer(reptiles:aggregated) %>%
  mutate(type = "easement")

fee_time <- as_tibble(fee_richness) %>%
  mutate(area = st_area(geometry)) %>%
  mutate(Accss_D = ifelse(Dat_Est < 2010 & Dat_Est > 2000,"2000-2010", 
                          ifelse(Dat_Est > 2010, "2011-2019", NA)),
         reptiles = rptl_rc,
         amphibians = amphbn_,
         mammals= mmml_rc,
         birds = brd_rch,
         fish = fsh_rch)%>%
  mutate(aggregated = reptiles + amphibians + mammals + birds + fish) %>%
  mutate(Accss_D = factor(Accss_D, levels = c("2000-2010","2011-2019"))) %>%
  select(Accss_D, reptiles:aggregated) %>%
  pivot_longer(reptiles:aggregated) %>%
  mutate(type = "protected area")

```

```{r sr_time, fig.width=5, fig.height=3, dpi = 600}
easement_time %>% bind_rows(fee_time) %>%
  group_by(type) %>%
  filter(name == "aggregated") %>%
  remove_missing() %>%
  ggplot(aes(x = Accss_D, y = log(value), fill = type)) + geom_boxplot() +
  facet_wrap(~type, scales = "free", ncol = 3) +
  theme_classic() +
    scale_fill_manual(values=c("#0072B2", "#E69F00")) +
  theme(axis.title.x =element_blank()) +
  theme(legend.title = element_blank(),
        legend.position = "none") +
  labs(y = "log mean species richness") +
   theme(axis.text=element_text(size=8),
        axis.title=element_text(size=8),
        panel.border = element_rect(colour = "black", fill=NA),
        legend.box.background = element_rect(colour = "black"),
        legend.text = element_text(size = 8))
```


Regional drivers

```{r}
background_richness <- st_read("../data/output/background_richness_bystate.shp")
```

```{r}
easement <- easement_richness %>%
  mutate(area = st_area(geometry)) %>%
  group_by(Stat_Nm) %>%
  mutate(st_area = sum(area)) %>%
  mutate(perc_area = area/st_area) %>%
  mutate(reptiles = mean(rptl_rc, na.rm = TRUE)*perc_area,
         amphibians = mean(amphbn_, na.rm = TRUE)*perc_area,
         mammals= mean(mmml_rc, na.rm = TRUE)*perc_area,
         birds = mean(brd_rch, na.rm = TRUE)*perc_area,
         fish = mean(fsh_rch, na.rm = TRUE)*perc_area) %>%
    ungroup() 

fee <- fee_richness %>%
  mutate(area = st_area(geometry)) %>%
  group_by(Stat_Nm) %>%
  mutate(st_area = sum(area)) %>%
  mutate(perc_area = area/st_area) %>%
  mutate(reptiles = mean(rptl_rc, na.rm = TRUE)*perc_area,
         amphibians = mean(amphbn_, na.rm = TRUE)*perc_area,
         mammals= mean(mmml_rc, na.rm = TRUE)*perc_area,
         birds = mean(brd_rch, na.rm = TRUE)*perc_area,
         fish = mean(fsh_rch, na.rm = TRUE)*perc_area) %>%
    ungroup() 
```


```{r}
richness_easement <- dplyr::as_tibble(easement) %>%
  dplyr::mutate(type = "easement") %>%
  dplyr::group_by(type, Stat_Nm, st_area) %>%
  dplyr::summarize(reptiles = sum(reptiles, na.rm = TRUE),
            amphibians = sum(amphibians, na.rm = TRUE),
            mammals= sum(mammals, na.rm = TRUE),
            birds = sum(birds, na.rm = TRUE),
            fish = sum(fish, na.rm = TRUE)) %>%
  ungroup() %>%
  mutate(richness_ce = reptiles+amphibians+mammals+birds+fish) %>%
  select(Stat_Nm, richness_ce, st_area) %>%
  rename(st_area_ce = st_area)

  
richness_pa <- dplyr::as_tibble(fee) %>%
  mutate(type = "protected area") %>%
  #filter(GAP_Sts == "2") %>%
  group_by(type, Stat_Nm, st_area) %>%
  dplyr::summarize(reptiles = sum(reptiles, na.rm = TRUE),
            amphibians = sum(amphibians, na.rm = TRUE),
            mammals= sum(mammals, na.rm = TRUE),
            birds = sum(birds, na.rm = TRUE),
            fish = sum(fish, na.rm = TRUE)) %>%
  ungroup() %>%
  mutate(richness_pa = reptiles+amphibians+mammals+birds+fish) %>%
  select(Stat_Nm, richness_pa, st_area) %>%
  rename(st_area_pa = st_area)
```

```{r}
richness_protected <-richness_pa %>%
  left_join(richness_easement) %>%
  mutate(richness_pa = as.numeric(richness_pa),
         richness_ce = as.numeric(richness_ce),
         st_area_pa = as.numeric(st_area_pa),
         st_area_ce = as.numeric(st_area_ce))
```

```{r}
regions <- read_csv("../data/regions.csv") %>% select(-X3) %>%
  rename(Stat_Nm = State)
```

```{r}
richness_protected %>%
  left_join(regions) %>%
  ggplot(aes(x= richness_pa, y = richness_ce, col = Region)) + geom_point()
```

```{r}
richness_protected %>%
  left_join(regions) %>%
  ggplot(aes(x= richness_ce/richness_pa, y = st_area_ce/st_area_pa, col = Region)) + geom_point()
```

