---
title: "maps"
author: "Millie Chapman"
date: "3/7/2021"
output: github_document
---

```{r}
library(tidyverse)
library(sf)
```

```{r}
usa <- st_read("../data/gadm36_USA_shp/gadm36_USA_0.shp") %>%
  mutate(area = st_area(geometry)) 
```


```{r}
easement <- st_read("../data/PADUS2_0_Shapefiles/PADUS2_0Easement.shp")
fee <- st_read("../data/PADUS2_0_Shapefiles/PADUS2_0Fee.shp")
```


```{r, warning=FALSE}
fee <- fee %>% 
  dplyr::filter(SHAPE_Area > 1,
                GAP_Sts == "1"|GAP_Sts == "2") %>%
  mutate(area = st_area(geometry))
```

```{r, warning=FALSE}
easements <- easement %>% 
  dplyr::filter(GAP_Sts == "1"|GAP_Sts == "2") %>%
    mutate(area = st_area(geometry))
```


```{r}
fee_area <- as_tibble(fee) %>% 
  mutate(type = "protected area") %>%
  group_by(type) %>%
  summarise(area = sum(area))

easement_area <- easement %>% 
  mutate(type = "easement",
         area = st_area(geometry))
```

```{r area_plot, fig.height= 2.5, fig.width = 2.5, dpi = 500}
as_tibble(easement_area) %>%
  group_by(type) %>%
  summarise(area = sum(area)) %>%
  bind_rows(fee_area) %>%
  ggplot(aes(x=type, y = as.numeric(area)/10^9, fill = type)) + geom_bar(stat= "identity") + 
  theme_classic() +
    scale_fill_manual(values=c("#0072B2", "#E69F00")) +
  theme(axis.title.x =element_blank()) +
  theme(legend.title = element_blank(),
        legend.position = "none") +
  labs(y = "Total area (10^9 ha)") +
   theme(axis.text=element_text(size=8),
        axis.title=element_text(size=8),
        panel.border = element_rect(colour = "black", fill=NA),
        legend.box.background = element_rect(colour = "black"),
        legend.text = element_text(size = 8))
```

```{r}
fee_box <- as_tibble(fee) %>%
  mutate(type = "protected area") %>%
  select(type, area)
```


```{r box_plot, fig.height= 2.5, fig.width = 2.5, dpi = 500}
as_tibble(easement_area) %>% select(type, area) %>%
  bind_rows(fee_box) %>%
  ggplot(aes(x=type, y = log(as.numeric(area)), fill = type)) + geom_boxplot() +
  theme_classic() +
    scale_fill_manual(values=c("#0072B2", "#E69F00")) +
  theme(axis.title.x =element_blank()) +
  theme(legend.title = element_blank(),
        legend.position = "none") +
  labs(y = "log area (per parcel)") +
   theme(axis.text=element_text(size=8),
        axis.title=element_text(size=8),
        panel.border = element_rect(colour = "black", fill=NA),
        legend.box.background = element_rect(colour = "black"),
        legend.text = element_text(size = 8))
```


```{r}
mainland <- ggplot() + 
  geom_sf(data = usa, fill = "#DCDCDC", lwd = 0)+
  geom_sf(data = easement, fill = "#0072B2",lwd = 0) +
  geom_sf(data = fee, fill = "#E69F00",lwd = 0) +
  coord_sf(crs = st_crs(2163), xlim = c(-2500000, 2500000), ylim = c(-2300000, 
         730000))+ theme_minimal() +
  theme(panel.border = element_rect(colour = "black", fill=NA))
mainland
```

```{r}
alaska <- ggplot() +
    geom_sf(data = usa, fill = "#DCDCDC", lwd = 0)+
     geom_sf(data = easement, fill = "#0072B2", lwd= 0) +
     geom_sf(data = fee, fill = "#E69F00", lwd = 0) +
     coord_sf(crs = st_crs(3467), xlim = c(-2400000, 1600000), ylim = c(200000, 
         2500000), expand = FALSE, datum = NA) +theme_minimal() +
   theme(panel.border = element_rect(colour = "black", fill=NA))
hawaii  <- ggplot() +
    geom_sf(data = usa, fill = "#DCDCDC", lwd = 0)+
       geom_sf(data = easement, fill = "#0072B2", color = "#0072B2") +
       geom_sf(data = fee, fill = "#E69F00", color = "#E69F00") +
     coord_sf(crs = st_crs(4135), xlim = c(-161, -154), ylim = c(18, 
         23), expand = FALSE, datum = NA) +theme_minimal() +
     theme(panel.border = element_rect(colour = "black", fill=NA))
```


```{r, fig.height= 5, fi.width = 5, dpi = 600}
mainland +
 annotation_custom(
      grob = ggplotGrob(alaska),
      xmin = -2800000,
      xmax = -2750000 + (1600000 - (-2400000))/2.5,
      ymin = -2450000,
      ymax = -2450000 + (2500000 - 200000)/2.5
  ) +
  annotation_custom(
      grob = ggplotGrob(hawaii),
      xmin = -1250000,
      xmax = -1250000 + (-154 - (-161))*120000,
      ymin = -2450000,
      ymax = -2450000 + (23 - 18)*120000
  )
```



