---
title: "species_richness"
author: "Millie Chapman"
date: "2/19/2021"
output: github_document
---

```{r}
library(rasterSp)
library(rgdal)
library(sf)
library(raster)
library(fasterize)
library(tidyverse)
```


```{r}
background <- st_read("../data/gadm36_USA_shp/gadm36_USA_0.shp")
```


```{r message=FALSE, warning=FALSE}
mammals <- read_sf("../data/IUCN/MAMMALS_TERRESTRIAL_ONLY/MAMMALS_TERRESTRIAL_ONLY.shp", 
                   query = "SELECT binomial FROM MAMMALS_TERRESTRIAL_ONLY WHERE presence < 2 AND seasonal < 3")

amphibians <- read_sf("../data/IUCN/AMPHIBIANS/AMPHIBIANS.shp", 
                      query = "SELECT binomial FROM AMPHIBIANS WHERE presence < 2 AND seasonal < 3")

reptiles <- read_sf("../data/IUCN/REPTILES/REPTILES.shp", query = "SELECT binomial FROM REPTILES WHERE presence < 2 AND seasonal < 3")
```


```{r}
mammals_usa <- st_crop(mammals, background)
```


```{r}
template_raster <- raster(mammals, res = 1/6, crs = crs(mammals))
```

```{r}
mammal_richness <- fasterize(mammals, template_raster, fun="sum")
reptile_richness <- fasterize(reptiles, template_raster, fun="sum")
amphibian_richness <- fasterize(amphibians, template_raster, fun="sum")
```

```{r}
rm(mammals)
rm(reptiles)
rm(amphibians)
```

```{r}
fw_fish1 <- read_sf("../data/IUCN/FW_GROUP/FW_GROUP_PART1.shp", query = "SELECT binomial FROM FW_GROUP_PART1 WHERE presence < 2 AND seasonal < 3")

fw1_richness <- fasterize(fw_fish1, template_raster, fun="sum")
```

```{r}
fw_fish2 <- st_read("../data/IUCN/FW_GROUP/FW_GROUP_PART2.shp", query = "SELECT binomial FROM FW_GROUP_PART2 WHERE presence < 2 AND seasonal < 3")

fw2_richness <- fasterize(fw_fish2, template_raster, fun="sum")

fw_richness <- fw1_richness + fw2_richness
```

```{r}
rm(fw_fish1)
rm(fw_fish2)
rm(fw2_richness)
rm(fw1_richness)
```

```{r}
fw_fish3 <- st_read("../data/IUCN/FW_GROUP/FW_GROUP_PART3.shp", query = "SELECT binomial FROM FW_GROUP_PART3 WHERE presence < 2 AND seasonal < 3")

fw3_richness <- fasterize(fw_fish3, template_raster, fun="sum")
fw_richness <- fw_richness + fw3_richness
rm(fw3_richness)
rm(fw_fish3)
```

```{r}
fw_fish4 <- st_read("../data/IUCN/FW_GROUP/FW_GROUP_PART4.shp", query = "SELECT binomial FROM FW_GROUP_PART4 WHERE presence < 2 AND seasonal < 3")

fw4_richness <- fasterize(fw_fish4, template_raster, fun="sum")
fw_richness <- fw_richness + fw4_richness
rm(fw4_richness)
rm(fw_fish4)
```

```{r}
fw_fish5 <- st_read("../data/IUCN/FW_GROUP/FW_GROUP_PART5.shp", query = "SELECT binomial FROM FW_GROUP_PART5 WHERE presence < 2 AND seasonal < 3")

fw5_richness <- fasterize(fw_fish5, template_raster, fun="sum")
fw_richness <- fw_richness + fw5_richness
rm(fw5_richness)
rm(fw_fish5)
```

```{r}
fw_fish6 <- st_read("../data/IUCN/FW_GROUP/FW_GROUP_PART6.shp", query = "SELECT binomial FROM FW_GROUP_PART6 WHERE presence < 2 AND seasonal < 3")

fw6_richness <- fasterize(fw_fish6, template_raster, fun="sum")
fw_richness <- fw_richness + fw6_richness
rm(fw6_richness)
rm(fw_fish6)
```

```{r}
birds <- read_sf("../data/IUCN/BOTW/birdlife_all.shp", query = "SELECT binomial FROM birdlife_all WHERE presence < 2 AND seasonal < 3")

bird_richness <- fasterize(birds, template_raster, fun="sum")
```

```{r}
rm(birds)
rm(template_raster)
```

```{r}
easement <- st_read("../data/PADUS2_0_Shapefiles/PADUS2_0Easement.shp")
fee <- st_read("../data/PADUS2_0_Shapefiles/PADUS2_0Fee.shp")
```


```{r, warning=FALSE}
fee <- fee %>% 
  dplyr::filter(SHAPE_Area > 1,
                GAP_Sts == "1"|GAP_Sts == "2")

fee <- fee %>%
  dplyr::mutate(valid = st_is_valid(fee)) %>%
  dplyr::filter(valid == "TRUE")
```

```{r}
NAvalue(mammal_richness) <- 0
NAvalue(reptile_richness) <- 0
NAvalue(amphibian_richness) <- 0
NAvalue(fw_richness) <- 0
NAvalue(bird_richness) <- 0
```

```{r, warning=FALSE}
easement1 <- easement %>% 
  dplyr::filter(GAP_Sts == "1")
```

```{r, warning=FALSE}
easement2 <- easement %>% 
  dplyr::filter(GAP_Sts == "2")
```

```{r}
fee_richness <- fee  %>%
  dplyr::mutate(mammal_richness = raster::extract(mammal_richness, fee, fun=mean, na.rm = TRUE),
                reptile_richness = raster::extract(reptile_richness, fee, fun=mean, na.rm = TRUE),
                amphibian_richness = raster::extract(amphibian_richness, fee, fun=mean, na.rm = TRUE),
                fish_richness = raster::extract(fw_richness, fee, fun=mean, na.rm = TRUE),
                bird_richness =  raster::extract(bird_richness, fee, fun=mean, na.rm = TRUE))
```

```{r}
st_write(fee_richness, "../data/output/fee_richness.shp",append = FALSE)
```

```{r}
easement_richness1 <- easement1 %>%
  dplyr::mutate(mammal_richness = raster::extract(mammal_richness, easement1, fun=mean, na.rm = TRUE),
                reptile_richness = raster::extract(reptile_richness, easement1, fun=mean, na.rm = TRUE),
                amphibian_richness = raster::extract(amphibian_richness, easement1, fun=mean, na.rm = TRUE),
               fish_richness = raster::extract(fw_richness, easement1, fun=mean, na.rm = TRUE),
              bird_richness =  raster::extract(bird_richness, easement1, fun=mean, na.rm = TRUE)) 
```

```{r}
st_write(easement_richness1, "../data/output/easement_richness1.shp", append = FALSE)
```

```{r}
easement_richness2 <- easement2 %>%
  dplyr::mutate(mammal_richness = raster::extract(mammal_richness, easement2, fun=mean, na.rm = TRUE),
                reptile_richness = raster::extract(reptile_richness, easement2, fun=mean, na.rm = TRUE),
                amphibian_richness = raster::extract(amphibian_richness, easement2, fun=mean, na.rm = TRUE),
               fish_richness = raster::extract(fw_richness, easement2, fun=mean, na.rm = TRUE),
              bird_richness =  raster::extract(bird_richness, easement2, fun=mean, na.rm = TRUE)) 
```

```{r}
st_write(easement_richness2, "../data/output/easement_richness2.shp", append = FALSE)
```


```{r, warning=FALSE}
background_richness <- background %>%
  dplyr::mutate(mammal_richness = raster::extract(mammal_richness, background, fun=mean, na.rm = TRUE),
                reptile_richness = raster::extract(reptile_richness, background, fun=mean, na.rm = TRUE),
                amphibian_richness = raster::extract(amphibian_richness, background, fun=mean, na.rm = TRUE),
                fish_richness = raster::extract(fw_richness, background, fun=mean, na.rm = TRUE),
                bird_richness =  raster::extract(bird_richness, background, fun=mean, na.rm = TRUE)) 
```

```{r}
st_write(background_richness, "../data/output/background_richness.shp", append = FALSE)
```




