---
title: "potential-figures"
author: "Millie Chapman"
date: "3/2/2021"
output: github_document
---

```{r}
library(sf)
library(tidyverse)
```

```{r}
fee_richness <- st_read("../data/output/fee_richness_allpublic.shp")
```


```{r}
background_richness <- st_read("../data/output/background_richness_bystate.shp")
```

```{r}
regions <- read_csv("../data/regions.csv") %>% select(-X3)
names <- as_tibble(fee_richness) %>%
  select(Stat_Nm, d_Stt_N) %>% unique() %>%
  rename(State = Stat_Nm) %>%
  left_join(regions)%>%
  rename(NAME_1 = State)
```

area weight biodiversity 
```{r}
fee <- fee_richness %>%
  filter(GAP_Sts == "1" | GAP_Sts == "2") %>%
  mutate(area = st_area(geometry)) %>%
  group_by(Stat_Nm) %>% 
  mutate(state_area = sum(area))

fee <- fee %>%
  mutate(perc_area = area/state_area) %>%
  mutate(reptiles = mean(rptl_rc, na.rm = TRUE)*perc_area,
         amphibians = mean(amphbn_, na.rm = TRUE)*perc_area,
         mammals= mean(mmml_rc, na.rm = TRUE)*perc_area,
         birds = mean(brd_rch, na.rm = TRUE)*perc_area,
         fish = mean(fsh_rch, na.rm = TRUE)*perc_area)
```


```{r}
richness_pa <- dplyr::as_tibble(fee) %>%
  mutate(type = "public") %>%
  #filter(GAP_Sts == "2") %>%
  group_by(type, Stat_Nm, d_Stt_N) %>%
  dplyr::summarize(reptiles = as.numeric(sum(reptiles, na.rm = TRUE)),
            amphibians = as.numeric(sum(amphibians, na.rm = TRUE)),
            mammals= as.numeric(sum(mammals, na.rm = TRUE)),
            birds = as.numeric(sum(birds, na.rm = TRUE)),
            fish = as.numeric(sum(fish, na.rm = TRUE)),
            area = as.numeric(sum(area))) %>%
  mutate(NAME_1 = d_Stt_N) 
```

```{r}
richness_all <- as_tibble(background_richness) %>%
  mutate(area = st_area(geometry)) %>%
  left_join(names, by = ) %>%
  group_by(NAME_1) %>% 
  mutate(state_area = sum(area)) 

richness_all <- richness_all %>%
  mutate(perc_area = area/state_area) %>%
  mutate(reptiles = mean(rptl_rc, na.rm = TRUE)*perc_area,
         amphibians = mean(amphbn_, na.rm = TRUE)*perc_area,
         mammals= mean(mmml_rc, na.rm = TRUE)*perc_area,
         birds = mean(brd_rch, na.rm = TRUE)*perc_area,
         fish = mean(fsh_rch, na.rm = TRUE)*perc_area)

richness_background<- dplyr::as_tibble(richness_all) %>%
  mutate(type = "background") %>%
  #filter(GAP_Sts == "2") %>%
  group_by(NAME_1, type) %>%
  dplyr::summarize(reptiles = as.numeric(sum(reptiles, na.rm = TRUE)),
            amphibians = as.numeric(sum(amphibians, na.rm = TRUE)),
            mammals= as.numeric(sum(mammals, na.rm = TRUE)),
            birds = as.numeric(sum(birds, na.rm = TRUE)),
            fish = as.numeric(sum(fish, na.rm = TRUE)),
            area = as.numeric(sum(area)))
```

```{r}
easement_richness1 <- st_read("../data/output/easement_richness1.shp")
easement_richness2 <- st_read("../data/output/easement_richness2.shp")
easement_richness <- easement_richness1 %>%
  bind_rows(easement_richness2)

```


```{r}
easement <- easement_richness %>%
  filter(GAP_Sts == "1" | GAP_Sts == "2") %>%
  mutate(area = st_area(geometry)) %>%
  group_by(Stat_Nm) %>% 
  mutate(state_area = sum(area))

easement <- easement %>%
  mutate(perc_area = area/state_area) %>%
  mutate(reptiles = mean(rptl_rc, na.rm = TRUE)*perc_area,
         amphibians = mean(amphbn_, na.rm = TRUE)*perc_area,
         mammals= mean(mmml_rc, na.rm = TRUE)*perc_area,
         birds = mean(brd_rch, na.rm = TRUE)*perc_area,
         fish = mean(fsh_rch, na.rm = TRUE)*perc_area)
```


```{r}
richness_easement <- dplyr::as_tibble(easement) %>%
  mutate(type = "easement") %>%
  #filter(GAP_Sts == "2") %>%
  group_by(type, Stat_Nm, d_Stt_N) %>%
  dplyr::summarize(reptiles = as.numeric(sum(reptiles, na.rm = TRUE)),
            amphibians = as.numeric(sum(amphibians, na.rm = TRUE)),
            mammals= as.numeric(sum(mammals, na.rm = TRUE)),
            birds = as.numeric(sum(birds, na.rm = TRUE)),
            fish = as.numeric(sum(fish, na.rm = TRUE)),
            area = as.numeric(sum(area))) %>%
  mutate(NAME_1 = d_Stt_N) %>% ungroup()
```


```{r}
regions_states <- richness_pa %>%
  select(Stat_Nm, d_Stt_N) %>%
  rename(State = Stat_Nm) %>%
  left_join(regions) %>% ungroup() %>%
  rename(NAME_1 = d_Stt_N) %>%
  select(State:Region)
```

```{r}
richness_table <- richness_pa1 %>%
  bind_rows(richness_private1) %>%
  pivot_longer(mammals:reptiles) %>%
  select(type, area, name, value) %>%
  group_by(type) %>%
  mutate(total_area = sum(area)/5) %>% ungroup()
```


```{r}
richness <- richness_background %>%
  bind_rows(richness_pa) %>%
  bind_rows(richness_easement) %>%
  pivot_longer(reptiles:fish) %>%
  left_join(regions_states, by = "NAME_1")
```

```{r}
richness_background <- richness %>%
  filter(type == "background") 
```


```{r fig.width=7, fig.height=4}
library(ggplot2)
library(ungeviz)
richness %>%
  filter(type != "background") %>%
  drop_na(Region) %>%
  ggplot() + 
  scale_fill_manual(values=c("#0072B2", "#E69F00", "black")) +
  geom_bar(aes(x= name, y= as.numeric(value), fill = type),
                                  stat = "identity", width=0.65,
                                  position=position_dodge(width=0.8)) +
  geom_hpline(data = richness_background, aes(x=name, y =value), stat = "identity", height = 0.4, lwd = .75) +
  #geom_point(richness_background, mapping = aes(x = name, y= value), pch = 19) +
  theme_minimal() +
  theme(axis.title.y =element_blank()) +
  theme(legend.title = element_blank()) + coord_flip() +
  theme(legend.position = c(0.9, 0.9)) +
   theme(axis.text=element_text(size=8),
        axis.title=element_text(size=10),
        panel.border = element_rect(colour = "black", fill=NA),
        legend.box.background = element_rect(colour = "black"),
        legend.text = element_text(size = 8)) +
  guides(shape = guide_legend(override.aes = list(size = 5))) + 
  facet_wrap(~Region)
```


```{r fig.width=3, fig.height=3}
ca_background <- richness_background %>%
  filter(NAME_1 == "California" | NAME_1 == "Alaska" |NAME_1 == "Massachusetts" | NAME_1 == "South Carolina")

richness %>%
  filter(type != "background") %>%
  filter(NAME_1 == "California" | NAME_1 == "Alaska" |NAME_1 == "Massachusetts" | NAME_1 == "South Carolina") %>%
  drop_na(Region) %>%
  ggplot() + 
  scale_fill_manual(values=c("#0072B2", "#E69F00", "black")) +
  geom_bar(aes(x= name, y= as.numeric(value), fill = type),
                                  stat = "identity", width=0.65,
                                  position=position_dodge(width=0.8)) +
  geom_hpline(data = ca_background, aes(x=name, y =value), stat = "identity", height = 0.4, lwd = .75) +
  #geom_point(ca_background, mapping = aes(x = name, y= value), pch = 19) +
  theme_minimal() +
  theme(axis.title.y =element_blank()) +
  theme(legend.title = element_blank()) + coord_flip() +
  theme(legend.position = c(0.9, 0.9)) +
   theme(axis.text=element_text(size=8),
        axis.title=element_text(size=10),
        panel.border = element_rect(colour = "black", fill=NA),
        legend.box.background = element_rect(colour = "black"),
        legend.text = element_text(size = 8)) +
  guides(shape = guide_legend(override.aes = list(size = 5))) + 
  facet_wrap(~NAME_1)
```
```{r}

```

