---
title: "public_private_all"
author: "Millie Chapman"
date: "4/3/2021"
output: github_document
---

```{r}
library(sf)
library(tidyverse)
```

## ALL RICHNESS

```{r}
fee_richness <- read_sf("../data/output/fee_richness_allpublic.shp") %>%
  mutate(area = st_area(geometry))
```

```{r}
fee_richness_all <- as_tibble(fee_richness) %>%
  #filter(GAP_Sts == "1" |GAP_Sts == "2") %>%
  mutate(mmml_rc = replace_na(mmml_rc,0),
         rptl_rc = replace_na(rptl_rc,0),
         amphbn_ = replace_na(amphbn_,0),
         fsh_rch = replace_na(fsh_rch,0),
         brd_rch = replace_na(brd_rch,0)) %>%
  mutate(PA_CE = "public") %>%
  group_by(PA_CE) %>%
  mutate(total_area = sum(area)) %>%
  ungroup() %>%
  mutate(amphibians = amphbn_*area/total_area,
         birds = brd_rch*area/total_area,
         mammals = mmml_rc*area/total_area,
         fish = fsh_rch*area/total_area,
         reptiles = rptl_rc*area/total_area) %>%
  group_by(PA_CE) %>%
  summarise(amphibians = sum(amphibians),
         birds = sum(birds),
         mammals = sum(mammals),
         fish = sum(fish),
         reptiles = sum(reptiles),
         area = sum(area)) %>% ungroup() %>%
  mutate(amphibians = as.numeric(amphibians),
         birds = as.numeric(birds),
         mammals = as.numeric(mammals),
         fish = as.numeric(fish),
         reptiles = as.numeric(reptiles))
```

```{r}
background_richness <- st_read("../data/output/background_richness.shp") %>%
  mutate(area = st_area(geometry))
```

```{r}
us_area <- sum(background_richness$area)
```

```{r}
public_private <- as_tibble(background_richness) %>%
  select(-GID_0) %>%
  rename(
        amphibians_all = "amphbn_",
         birds_all = "brd_rch",
         mammals_all = "mmml_rc",
         fish_all = "fsh_rch",
         reptiles_all = "rptl_rc",
        area_all = "area") %>%
  select(-geometry) %>%
  bind_cols(fee_richness_all)
```

```{r}
private <- public_private %>%
  mutate(area_pr = area_all-area) %>%
  mutate(mammals= (mammals_all*area_all - mammals*area)/area_pr,
         reptiles= (reptiles_all*area_all - reptiles*area)/area_pr,
         amphibians= (amphibians_all*area_all - amphibians*area)/area_pr,
         fish= (fish_all*area_all - fish*area)/area_pr,
         birds= (birds_all*area_all - birds*area)/area_pr) %>%
  select(PA_CE:reptiles) %>%
  mutate(PA_CE = "private") %>%
  mutate(amphibians = as.numeric(amphibians),
         birds = as.numeric(birds),
         mammals = as.numeric(mammals),
         fish = as.numeric(fish),
         reptiles = as.numeric(reptiles))
```

```{r}
public_private <- private %>%
  bind_rows(fee_richness_all) %>%
  select(-area) %>%
  pivot_longer(-PA_CE) %>%
  rename(type = "PA_CE") %>% ungroup()
```

```{r}
write_csv(public_private, "../data/private_public_richness.csv", append = FALSE)
```

```{r}
private_public_richness1 <- read_csv("../data/private_public_richness.csv") 
```

## future

```{r}
fee_exp <- st_read("../data/GEE/feeexpnum.shp") %>%
  mutate(area = st_area(geometry)) %>%
  mutate(PA_CE = "public") %>%
  group_by(PA_CE) %>%
  mutate(total_area = sum(area)) %>% ungroup()

fee_exp <- as_tibble(fee_exp) %>%
  select(Date_Est, GAP_Sts, area,State_Nm,  num, total_area, PA_CE) 
  
fee_future <- read_csv("../data/climate-distributions/fee_futurespp_all_numbered.csv") %>%
  rename(amphibians = "b1",
         birds = "b1_1",
         mammals = "b1_2",
         plants = "b1_3",
         reptiles = "b1_4") %>%
  #drop_na(mammals,reptiles,amphibians, birds) %>%
  mutate(mammals = replace_na(mammals,0),
        reptiles = replace_na(reptiles,0),
         amphibians = replace_na(amphibians,0),
         #fsh_rch = replace_na(fsh_rch,0),
        birds = replace_na(birds,0)) %>%
  select(amphibians:num) %>%
  left_join(fee_exp, by = "num") %>%
  group_by(PA_CE) %>%
  mutate(total_area = sum(area)) %>%
  ungroup() %>%
  arrange(Date_Est) %>%
  mutate(amphibians = amphibians*area/total_area,
         birds = birds*area/total_area,
         mammals = mammals*area/total_area,
        # plants = plants*area/total_area,
         reptiles = reptiles*area/total_area) %>%
  group_by(PA_CE) %>%
  summarise(amphibians = sum(amphibians),
         birds = sum(birds),
         mammals = sum(mammals),
        # fish = sum(fish),
         reptiles = sum(reptiles),
         area = sum(area)) %>% ungroup() %>%
  mutate(amphibians = as.numeric(amphibians),
         birds = as.numeric(birds),
         mammals = as.numeric(mammals),
        # fish = as.numeric(fish),
         reptiles = as.numeric(reptiles))
```

```{r}
background_future <- read_csv("../data/climate-distributions/background_futurespp_all.csv") %>%
  rename(amphibians = "b1",
         birds = "b1_1",
         mammals = "b1_2",
         plants = "b1_3",
         reptiles = "b1_4") %>%
  group_by(ADM0_NAME) %>%
  mutate(total_area = sum(Shape_Area)) %>%
  ungroup() %>%
  mutate(amphibians = amphibians*Shape_Area/total_area,
         birds = birds*Shape_Area/total_area,
         mammals = mammals*Shape_Area/total_area,
        # plants = plants*area/total_area,
         reptiles = reptiles*Shape_Area/total_area) %>%
  group_by(ADM0_NAME) %>%
  summarise(amphibians = sum(amphibians),
         birds = sum(birds),
         mammals = sum(mammals),
        # fish = sum(fish),
         reptiles = sum(reptiles),
         area_all = us_area) %>% ungroup() %>%
  mutate(amphibians_all = as.numeric(amphibians),
         birds_all = as.numeric(birds),
         mammals_all = as.numeric(mammals),
        # fish = as.numeric(fish),
         reptiles_all = as.numeric(reptiles)) %>%
  select(ADM0_NAME,amphibians_all:reptiles_all, area_all)
```


```{r}
public_private <-  background_future %>%
  bind_cols(fee_future)
```

```{r}
private <- public_private %>%
  mutate(area_pr = area_all-area) %>%
  mutate(mammals= (mammals_all*area_all - mammals*area)/area_pr,
         reptiles= (reptiles_all*area_all - reptiles*area)/area_pr,
         amphibians= (amphibians_all*area_all - amphibians*area)/area_pr,
        # fish= (fish_all*area_all - fish*area)/area_pr,
         birds= (birds_all*area_all - birds*area)/area_pr) %>%
  select(PA_CE:reptiles) %>%
  mutate(PA_CE = "private") %>%
  mutate(amphibians = as.numeric(amphibians),
         birds = as.numeric(birds),
         mammals = as.numeric(mammals),
        # fish = as.numeric(fish),
         reptiles = as.numeric(reptiles),
        richness= amphibians+birds+mammals+reptiles)
```

```{r}
public_private_future <- private %>%
  bind_rows(fee_future) %>%
  select(-area) %>%
  pivot_longer(-PA_CE) %>%
  rename(type = "PA_CE") %>% ungroup()
```

```{r}
write_csv(public_private_future, "../data/private_public_future.csv", append = FALSE)
```

## CRENVU


## SR
