---
title: "The promise of U.S. private lands for reaching 21st century conservation targets" 
author:
  - name: Melissa Chapman
    affiliation: espm
    footnote: Corresponding Author
  - name: Carl Boettiger
    affiliation: espm
  - name: Justin Brashares
    affiliation: espm
address:
  - code: espm
    address: "Dept. of Environmental Science, Policy, and Management, University of California Berkeley, Berkeley, CA, USA"
abstract: Coincident with an international movement to protect 30% of global land and sea over the next decade, the United States has committed to more than doubling its current protected land area by 2030. While publicly owned and managed protected areas have been the cornerstone of area-based conservation in the United States and globally over the past century, such areas are costly to establish and have shown limited capacity to protect areas of highest value for biodiversity protection and climate mitigation. Here we examine the potential contribution of private lands to reach biodiversity and climate mitigation targets in the United States. Using the largest national database of public and private land conservation alongside distributions of biodiversity priority areas, current and projected species richness and carbon sequestration for North America, we show that private land conservation in the form of conservation easements has been more effective than federal protected areas in targeting areas of high value for biodiversity and climate change mitigation. We also explore how private lands are more commonly in areas designated as high conservation priority, hold significantly higher species richness than public lands and also hold more vulnerable carbon per unit area. We expand on these results to explore the critical role, and potential pitfalls, of leveraging private land conservation to meet post-2020 conservation goals and reducing biodiversity loss in the United States. 
keywords:
  - 30x30, 
  - biodiversity,  
  - conservation easements, 
  - conservation targets, 
  - protected areas,
  - climate mitigation 
bibliography: references.bib
date: "`r Sys.Date()`"
output: rticles::elsevier_article  
csl: nature-climate-change.csl
layout: 3p # review # review = doublespace, 3p = singlespace, 5p = two-column
header-includes: 
  - \journal{TBD}
  - \graphicspath{{ext-figs/}}
  - \usepackage{float}
  - \linenumbers
  - \usepackage{setspace}\doublespacing
---

# Introduction

Following another decade of accelerating biodiversity loss [@Buchanan2020a], the Convention on Biological Diversity (CBD) is promoting a post-2020 transnational agreement on biodiversity conservation. 
Largely coalesced around the promise of protecting 30% of the Earth’s land and sea by 2030 (“30x30”), this agreement will influence the next decade of global conservation policies and biodiversity outcomes [@Maxwell2020a; @Tsioumani2020; @Diversity2020]. 
In hopes of not repeating the shortcomings of past area-based conservation agreements [@Buchanan2020a], scientists and policymakers have emphasized modern definitions of area-based protection that recognize "other effective area based conservation measures" (OECMs) beyond traditional protected areas [@Maxwell2020a]. Notably, there has been an emphasis on the importance of private and working land contributions to meeting biodiversity and climate mitigation goals [@Maxwell2020a; A t B; CA30x30].

The United States is among the first countries to pass a legal mandate in response to early drafts of the post-2020 CBD biodiversity targets [@Diversity2020].
In a 2021 Executive Order on “Tackling the Climate Crisis at Home and Abroad”, the Biden administration committed to conserving 30\% of United States lands and waters by the year 2030, with the broader goals of safeguarding food production and biodiversity while mitigating climate change (Exec. Order No. 14008, 2021). 
With less than 15% of current US lands permanently protected in areas managed for biodiversity [@GAP2018], meeting this target will require an unprecedented expansion of land protection over the next decade. 
While protected areas owned by state and federal agencies account for the majority of protected land in the U.S., they are legally cumbersome to implement (aside from National Monuments established under the Antiquities Act), costly, and have historically displaced communities and livelihoods [CITE]. 
Moreover, despite the increasing prevalence of spatial conservation planning and conservation prioritization [@McIntosh2017; @Sinclair2018a], several studies suggest protected areas created to date overlap poorly with priority areas for biodiversity conservation [@Maxwell2020a; @Jenkins2015].

In an attempt to meet ambitious area-based targets more equitably, while simultaneously reducing potential mismatches between lands managed for biodiversity and biodiversity distributions themselves, both federal and sub-national post-2020 legislation and proposed pathways to meeting the legislative targets in the U.S. have emphasized broader engagement with private and working land [CITE]. 
However, studies exploring the mismatch of protected areas and biodiversity have largely ignored how other area-based conservation measures, such as private land conservation, align with areas of high conservation priority [@Maxwell2020a; @Jenkins2015]. 
Without a systematic understanding of the relative capacity of private land conservation to target key biodiversity areas and opportunities for climate change mitigation, it is difficult to assess if the emphasis on private lands is a well-informed policy direction for expanding area-based conservation.

Private land protection measures, including private reserves, land trusts, and conservation easements,have long contributed to land conservation in the United States despite representing only a small fraction of the total land under protection [@WALLACE2008a]. 
While private land conservation takes many forms, conservation easements - voluntary legal agreements that permanently limit the uses of private land to protect conservation values - have garnered particular interest from conservation initiatives in the U.S. and elsewhere, due to their cost-efficacy and legal flexibility [@CortesCapano2019]. 
While a large body of literature has examined drivers and impacts of conservation easement adoption [@Stroman2017], management attributes [@Rissman2007], and efficacy [@Merenlender2004], quantifying the value of conservation easements for biodiversity at a national scale has been impeded by a lack of centralized data on parcel delineations. 
Fortunately, new products such as the U.S. National Conservation Easements Database (NCED; [@National2020]) now provide opportunities to visualize and analyze the relative efficacy of private land conservation measures in targeting areas of high conservation value.

Here, we used the national compilation of spatial data on conservation easements (NCED) to quantify the value of existing U.S. easements for protecting biodiversity and securing carbon. 
Using the NCED [@National2020] alongside distributions of biodiversity priority areas (8), current species richness (15; 16), projected species richness under climate change (17), and carbon sequestration in North America (18), we assessed the conservation value of easements in the United States relative to federal protected areas and unprotected lands.
We also tested if protected areas and conservation easements created in the last 20 years (2001-2020) showed increased targeting of priority areas for biodiversity conservation or climate mitigation. 
Taken together, our analyses explore the potential of private lands to complement traditional protected area contributions to meeting qualitative elements of 2030 conservation targets, such as climate change mitigation and climate resilience.

# Conservation in key biodiversity areas

Area-based conservation goals risk incentivizing the protection of cost-effective and opportunistically available land rather than land with high conservation and climate mitigation value (21). 
We find that unprotected private land is distributed in areas with higher mean species richness values than public land that is not managed for biodiversity. 
Similarly, conservation easements more effectively target areas with high species richness than public protected areas (Fig. 2). 
However, we find that neither public protected areas nor conservation easements have significantly improved their targeting of species richness over the past two decades (Fig. 3) despite the expansion of spatial biodiversity data (7) and the widely accepted Aichi Biodiversity Targets of the previous decade.

Conservation easements managed for biodiversity (GAP 1 and GAP 2) account for a significantly smaller total area than equivalently managed federal protected areas (Fig. \ref{fig:fig1}B). Additionally, conservation easements are on average significantly smaller per management unit than protected areas (Fig. \ref{fig:fig1}C). Over the past 20 years, conservation easements have increased in their rate of adoption relative to protected areas (Fig. \ref{fig:fig1}D). While conservation easements are typically smaller than protected areas, they are more likely to overlap with land identified as a biodiversity priority (Fig. \ref{fig:fig1}E).

# BOX 1: Post-2020 area based conservation policy across scales


# BOX 2: The trajectory of of public and private protected areas in the United States


# BOX 3: Targeting biodiversity hotspots


Both GAP 1 and 2 protected areas and conservation easements have higher mean species richness values than background U.S.  lands (all lands within U.S. borders), but lower mean richness values than all private lands (estimated as all lands not included in PAD-US Fee GAP 1-4; Methods and Materials) (Fig. \ref{fig:fig2}). Notably, GAP 1 and 2 easements have higher mean species richness than GAP 1 and 2 protected areas. This holds true across aggregate richness as well as birds, fish, and mammal richness, but is not true of amphibians or reptile richness alone (Fig. \ref{fig:fig2}). Overall, public lands (GAP 1-4) have significantly lower richness values across all taxa compared to private lands and compared to total background values across all U.S. lands. This holds true for all taxa (Fig. \ref{fig:fig2}). However, when looking only at vulnerable, endangered, and critically endangered (CRENVU) species, as well as small range species, protected areas have higher mean richness values compared to conservation easements (Supplemental information; Fig. S2). The patterns of private and public land distributions relative to species richness distributions have remained relatively constant across the past two decades (Fig. \ref{fig:fig3} and Fig. S1). 


While species richness is only one component of biodiversity, it is a commonly used proxy to prioritize and assess the distribution of protection relative to key biodiversity areas (22). 
Exploring biodiversity metrics such as functional and phylogenetic diversity, as well as other considerations commonly used in planning reserve networks such as complementarity and endemism, will be critical to prioritizing future investment in both private and public protected areas. Notably, more than half of threatened and endangered  species rely on private land for critical habitat (U.S. Fish and Wildlife Service, 1997). 
However, despite this reliance of threatened and endangered species on private lands, we found that the distributions of endangered, vulnerable, and small range species more closely track protected areas than conservation easements (SI Fig. S2), highlighting the importance of complementary approaches to land protection.

# Climate-resilient biodiversity conservation and land-based climate change mitigation

Under future climate change scenarios (high emissions: RCP 8.5 \cite{Lawler2020b}), conservation easements and protected areas closely track projected background mean species richness values across all U.S. land (Fig. \ref{fig:fig4}A). Notably, protected areas and conservation easements (GAP 1 and GAP 2) had very similar mean future richness values. While conservation easements have marginally improved their tracking of future richness patterns over the past decade (Fig. \ref{fig:fig4}C), protected areas have not (Fig. \ref{fig:fig4}C).  

Contributions to nature-based climate mitigation also varied significantly across protected areas and conservation easements. Unsurprisingly, given their larger land area, protected areas accounted for significantly more total above and below ground carbon (Fig. \ref{fig:fig5}A). However, conservation easements had higher above ground carbon on a per unit area basis (Fig. \ref{fig:fig5}B).

# Discussion




## Climate resilience and mitigation potential on private lands

As conservation practitioners decide where and how to protect land, considering the potential impacts of climate-driven species range shifts is critical to ensure resilient networks of protected lands over the next decade. Examples of misguided land conservation due to shifting ranges of critical species are plentiful (23). Our analysis shows that both protected areas and conservation easements were less targeted towards lands with high species richness under climate change (Fig. 4) compared to richness in current climate conditions (Fig. 2), suggesting that climate resilient biodiversity conservation will require more effective prioritization of lands that are projected to be important for biodiversity. Similar to our analysis of current species richness distributions, private land held the highest density of projected future species richness overall, and thus should be central in to designing climate resilient pathways to achieving 30% national protection.
While designing climate resilient biodiversity protections is important given current emissions trajectories, climate mitigation is critical to slowing climate change (24) and its impact on biodiversity (25; 26). Land-based climate mitigation pathways (among other emissions reductions pathways) are a central component of post-2020 area-based conservation targets (Exec. Order No. 14008, 2021). Unsurprisingly, conservation easements accounted for a significantly smaller portion of total above and below ground carbon than protected lands due to being only a fraction of the area of fee-owned protected areas (Fig. 5A). However, we found that conservation easements store significantly more above ground carbon than protected areas on a per unit area basis (Fig. 5B). We also found that private lands overall held the majority of land carbon in the U.S. (Supporting information; Fig. S3). Thus, these lands hold the greatest potential for significant progress towards land-based climate mitigation.

## Avoiding pitfalls of private land conservation

Despite the promise of private land contributions to biodiversity protection and climate mitigation, conservation easements and other private land protection measures have been criticized for ineffective management and monitoring, as well as inequitable access and outcomes. Private land protections are often opaque in their implemented management practices, particularly when compared to publicly managed lands (27). Furthermore, monitoring the impact of management practices on private land at a national scale is difficult and disjointed. Systematic monitoring of private lands will necessarily raise concerns of privacy, potentially dissuading adoption of agreements in key areas. Further, private land conservation measures, including conservation easements, may disproportionately benefit high income landowners, often limit public access, and are rooted in legacies of racial capitalism and environmental injustice (28). Mitigating these issues through broader community engagement, locally-defined monitoring protocols, and increasing public access will be critical to ensuring private land conservation contributes to the equity and access targets of post-2020 conservation goals. Finally, it is notable that conservation easements typically conserve smaller parcels than protected areas (Fig. 1C), potentially resulting in patchier landscapes and increasing the impact of edge effects (29). However, categorizing parcels of protection as either “small and targeted” or “large and mismatched” is a false dichotomy – parcel size of either conservation easements or protected areas is not correlated with species richness in the U.S. (Supporting information; Fig. S4). Even when accounting for area and state of protected areas and easements, easements had significantly higher richness values on a per parcel basis. Still, smaller parcels are likely to be more common in private land protections due to land ownership patterns in the United States. Thus, strategies to spatially cluster easements in high priority areas may help ameliorate edge effects and improve connectivity.

## Sub-national governance and private land conservation
While our analysis focused on private land conservation distributions at a national scale, development and
implementation of 30x30 legislation in the United States (and likely in other federalist countries) will largely be driven by sub-national governing bodies (4). 
On the sub-national scale in the U.S., private land protections have already been featured in a number of state-based 30x30 executive orders. A deeper exploration of the sub-national distribution of private and public land relative to biodiversity and carbon distributions will be critical to ensuring that policies align with the resources in a given governance unit, rather than assuming national scale patterns are relevant at smaller scales (30). While accounting for State in our analysis does not change the qualitative finding that easements better target areas of higher species richness (Table S3), comparative analyses will also be critical to understanding sociopolitical and ecological contexts that impact the value of easement to meeting large-scale conservation targets. Investigating differences in the conservation value of public and private lands across sub-national scales of governance may also help clarify the mechanisms driving the patterns of private and public land protections on the national scale. Additionally, understanding the structure of private land initiatives or public-private partnerships that are actively working towards spatial coordination of protection and biodiversity will be central to improving the targeting of protection over the next decade.

# Looking beyond private land


# Conclusion

Doubling the area of protected land in the United States over the next decade while also prioritizing land with high biodiversity and climate mitigation value will require significant investment in, and expansion of, private land conservation measures. 
We show that private land conservation instruments (conservation easements) better target areas with high conservation value (Fig. 1E), high species richness (Fig. 2) and high climate mitigation potential (Fig. 5) relative to federally-owned protected areas managed for biodiversity across the U.S. 
Importantly, our calculation of the average conservation value of public and private lands shows that private lands hold the majority of currently unprotected land with high biodiversity and climate mitigation value (Fig. 2 and Fig. 5). 
The urgency of expanding land protection to halt biodiversity loss will require flexible and expedient pathways to implementing protections on these lands. 
Meeting 30% area targets by 2030 will demand conservation actions that complement the historically unjust and legally cumbersome processes of implementing new national parks. 
Conservation easements and other forms of private land protection provide compelling and cost-effective alternatives.

Our analysis provides a national scale comparison of public and private lands conservation in the United States and highlights the importance of private land conservation for climate resilient biodiversity protection.
We show that private conservation is among the most effective and feasible land-based pathways to meeting U.S. land-based climate change mitigation goals by 2030. Despite numerous transnational and national environmental initiatives over the past fifty years, biodiversity loss, land conversion and climate change continue at unprecedented rates (31; 32). 
Meeting post-2020 biodiversity targets will require policy that synergistically expands biodiversity protection on both private and public lands while targeting areas of high conservation and climate mitigation value.

# Methods

### Data

We acquired protected area and conservation easement delineations from the United States Protected Area Database (PAD-US) (19). PAD-US compiles conservation easement data from the National Conservation Easements (NCED) (14) which contains over 130,000 easements (an estimated 60% of all U.S. easements; sensitivity analysis of results to missing data available in Supporting Information). 
We restricted our analysis of “protected areas” to land administered by public agencies (fee-owned) and managed for biodiversity (GAP 1 and GAP 2; Table S1). 
Similarly, we include only conservation easements that are managed for biodiversity (classified as GAP 1 or GAP 2) in the analysis of “protected” private land. 
Hereafter, we refer to these two categories of land designations as simply “protected areas” and “conservation easements”. 
Protected areas and conservation easements with invalid or missing geometries in the PAD-US dataset were excluded from the study. 
Our final dataset included 2579 protected areas and 1297 conservation easements managed under GAP 1 criteria (fully protected and allowing only for natural disturbances), and 313269 protected areas and 29351 conservation easements under GAP 2 criteria (fully protected and allowing for management action) (Fig. 1A; Table S1).
We compared biodiversity and climate mitigation values in our set of GAP 1 and 2 protected areas and conservation easements with those of all federally owned public lands and all lands held in private ownership.
For those analyses, we defined public lands as any land in the “fee-owned” PAD-US database (regardless of GAP status). 
All other lands were considered “private”.

Biodiversity priority areas were delineated using land in the 10th percentile of biodiversity priority index values in the United States (details on biodiversity priority indices can be found in (8)). 
Current species richness, CRENVU richness, and Range-size rarity was estimated using IUCN data, and calculated using raw IUCN ranges (version 2017-3) for amphibians, birds and mammals (CITE). While there are a number of alternative methods for mapping species richness (e.g., 17), there is no evidence to suggest that range maps would be systematically biased towards one given land protection measure over another.
We calculated future species richness using projected range distributions from Lawler et al. (2020) (17).
Future ranges were estimated for each species under three separate high emissions (RCP 8.5) climate change scenarios (17). 
We approximated future richness as the number of species in a given pixel (5 km2 resolution) using the mean of all three climate scenarios. To assess climate change mitigation values of lands across management types, we used vulnerable carbon maps, which estimate the carbon that would be lost under a land conversion event. (18).

### Analysis

We calculated mean species richness values for current and future species distributions across public and private management units in R (Supporting Information). 
Main figures represent overall differences in biodiversity metrics and carbon density (area-weighted means across all protected parcels). 
Differences in mean richness values across individual protected areas and conservation easements were assessed using t-tests (Supporting Information). 
We used propensity score matching to estimate the average marginal difference of mean species richness between conservation easements and protected areas accounting for the confounding effect of area of parcels and subnational governance (state) (Supporting Information).
Mean vulnerable carbon values per polygon were calculated using the same methods as above.


