---
title: "code-graveyard"
output: html_document
---


```{r}
# easements already filtered to GAP1-2 before extraction 
ag_e <- easements %>%
  mutate(Category = "easement") %>%
  group_by(Category, State_Nm) %>%
  mutate(total_area = sum(area)) %>%
  ungroup() %>%
  mutate(perc_area = area/total_area) %>%
  mutate(richness_all = richness_all*perc_area,
         RSR_all = RSR_all*perc_area,
         richness_crenvu= richness_crenvu*perc_area,
         carbon_vulnerable = carbon_vulnerable*perc_area) %>%
  group_by(Category, State_Nm, total_area) %>%
  summarise(richness_all = sum(richness_all, na.rm = TRUE),
         RSR_all = sum(RSR_all, na.rm = TRUE),
         richness_crenvu= sum(richness_crenvu, na.rm = TRUE),
         carbon_vulnerable = sum(carbon_vulnerable, na.rm = TRUE)) %>%
  ungroup()
```

```{r}
ag_f <- fee %>%
  filter(GAP_Sts == 1 | GAP_Sts == 2) %>%
    mutate(Category = "fee") %>%
  group_by(Category, State_Nm) %>%
  mutate(total_area = sum(area)) %>%
  ungroup() %>%
  mutate(perc_area = area/total_area) %>%
  mutate(richness_all = richness_all*perc_area,
         RSR_all = RSR_all*perc_area,
         richness_crenvu= richness_crenvu*perc_area,
         carbon_vulnerable = carbon_vulnerable*perc_area) %>%
  group_by(Category, State_Nm, total_area) %>%
  summarise(richness_all = sum(richness_all, na.rm = TRUE),
         RSR_all = sum(RSR_all, na.rm = TRUE),
         richness_crenvu= sum(richness_crenvu, na.rm = TRUE),
         carbon_vulnerable = sum(carbon_vulnerable, na.rm = TRUE)) %>% 
  ungroup() 
```

```{r}
ag_b <- background %>%
  rename(State_Nm = "STATE") %>%
  dplyr::select(State_Nm, richness_all:RSR_all, carbon_vulnerable, area) %>%
  rename(richness_all_b = richness_all,
         carbon_vulnerable_b = carbon_vulnerable)
```

```{r}
bivar_map_background <- ag_e %>%
  rbind(ag_f) %>%
  left_join(ag_b, by = "State_Nm")  %>%
  mutate(richness_all = (richness_all-richness_all_b)/richness_all_b,
         carbon_vulnerable= (carbon_vulnerable-carbon_vulnerable_b)/carbon_vulnerable_b) %>%
  dplyr::select(Category, State_Nm, richness_all, carbon_vulnerable)
```

```{r}
bivar_map_compar <- ag_e %>%
  mutate(richness_e = richness_all,
         carbon_e = carbon_vulnerable) %>%
  dplyr::select(State_Nm, richness_e, carbon_e) %>%
  left_join(ag_f) %>%
  mutate(richness = ifelse(richness_e-richness_all >0,1,0),
         carbon = ifelse(carbon_e-carbon_vulnerable>0,1,0)) %>%
  dplyr::select(State_Nm, richness, carbon)
```

```{r}
background_shp <- states(cb = FALSE) %>%
  rename(State_Nm = STUSPS) %>%
  st_transform(crs= st_crs(2163))
```

```{r}
subnational_map = bi_class(bivar_map_compar, x = richness, y = carbon, style = "quantile", dim = 2)

subnational_map <- subnational_map %>%
  left_join(background_shp)
```

```{r}
subnational_map_main <- ggplot() +
  geom_sf(data = subnational_map, mapping = aes(fill = bi_class, geometry= geometry), color = "black", size = 0.1, show.legend = FALSE) +
  coord_sf(crs = st_crs(2163), xlim = c(-2350000, 3000000), ylim = c(-2300000, 
         730000))+ theme_minimal() +
  theme(panel.border = element_rect(colour = "black", fill=NA)) +
  bi_scale_fill(pal = "DkCyan", dim = 2) +
  bi_theme() + theme(panel.border = element_rect(colour = "black", fill=NA))



legend <- bi_legend(pal = "DkCyan",
                    dim = 2,
                    xlab = "Higher richness in easements",
                    ylab = "Higher carbon in easements",
                    size = 4)
```

```{r legend, fig.width= 4, fig.height=4, dpi = 300}
legend
```


```{r}
AK_HI <- subnational_map %>%
  dplyr::select(NAME, bi_class) 
USA <- st_read("../data/US_shp/s_11au16.shp") %>%
  left_join(AK_HI)
```

```{r}
alaska <- ggplot() +
    geom_sf(data = USA,  aes(fill = bi_class), color = "black", size = 0.1, show.legend = FALSE)+
     coord_sf(crs = st_crs(3467), xlim = c(-2400000, 1600000), ylim = c(200000, 
         2500000), expand = FALSE, datum = NA) +theme_minimal() +
   theme(panel.border = element_rect(colour = "black", fill=NA)) +
  bi_scale_fill(pal = "DkCyan", dim = 2) +
  bi_theme() +  theme(panel.border = element_rect(colour = "black", fill=NA))


hawaii  <- ggplot() +
    geom_sf(data = USA, aes(fill = bi_class),color = "black", size = 0.1, show.legend = FALSE)+
     coord_sf(crs = st_crs(4135), xlim = c(-161, -154), ylim = c(18, 
         23), expand = FALSE, datum = NA) +theme_minimal() +
     theme(panel.border = element_rect(colour = "black", fill=NA)) +
  bi_scale_fill(pal = "DkCyan", dim = 2) +
  bi_theme() + theme(panel.border = element_rect(colour = "black", fill=NA))
```

```{r, fig.height= 5, fi.width = 5, dpi = 600}
a<-subnational_map_main +
 annotation_custom(
      grob = ggplotGrob(alaska),
      xmin = -2800000,
      xmax = -2750000 + (1600000 - (-2400000))/2.5,
      ymin = -2450000,
      ymax = -2450000 + (2500000 - 200000)/2.5
  ) +
  annotation_custom(
      grob = ggplotGrob(hawaii),
      xmin = -1250000,
      xmax = -1250000 + (-154 - (-161))*120000,
      ymin = -2450000,
      ymax = -2450000 + (23 - 18)*120000
  ) 
```




```{r figure5, fig.height=5, fig.width=6, dpi = 400}
a
```

public-private by state

```{r}
f2public <- fee %>%
  filter(Category == "fee") %>%
  mutate(Category = recode(Category, fee = "Public")) %>%
  group_by(Category, State_Nm) %>%
  mutate(total_area_public = sum(area)) %>%
  ungroup() %>%
  mutate(perc_area = area/total_area_public) %>%
  mutate(richness_all = richness_all*perc_area,
         RSR_all = RSR_all*perc_area,
         richness_crenvu= richness_crenvu*perc_area,
         carbon_vulnerable = carbon_vulnerable*perc_area) %>%
  group_by(Category, total_area_public) %>%
  summarise(richness_all = sum(richness_all, na.rm = TRUE),
         RSR_all = sum(RSR_all, na.rm = TRUE),
         richness_crenvu = sum(richness_crenvu, na.rm = TRUE),
         carbon_vulnerable = sum(carbon_vulnerable, na.rm = TRUE)) %>% 
  ungroup() 
```

```{r}
f2private <- f2public %>%
  dplyr::select(-Category) %>%
  cbind(ag_b) %>%
  mutate(area_private = total_area_ca-total_area_public) %>%
  mutate(richness_all = ((richness_all_b*total_area_ca)-(richness_all*total_area_public))/(area_private),
         RSR_all = ((RSR_all_b*total_area_ca)-(RSR_all*total_area_public))/(area_private),
         richness_crenvu = ((richness_crenvu_b*total_area_ca)-(richness_crenvu*total_area_public))/(area_private),
         carbon_vulnerable = ((carbon_vulnerable_b*total_area_ca)-(carbon_vulnerable*total_area_public))/(area_private)) %>%
  dplyr::select(richness_all:carbon_vulnerable, area_private) %>%
  mutate(Category = "Private") %>%
  rename(area = area_private)
```

public private

```{r}
public_private <- f2public %>%
  rename(area = total_area_public) %>%
  rbind(f2private) %>%
  mutate(bind= "a") %>%
  full_join(ag_b) %>%
  dplyr::mutate(`Species Richness` = (richness_all-richness_all_b)/richness_all_b,
                `Range-size Rarity`  = (RSR_all-RSR_all_b)/RSR_all_b,
                `CRENVU Richness` = (richness_crenvu-richness_crenvu_b)/richness_crenvu_b,
                carbon_vulnerable = (carbon_vulnerable-carbon_vulnerable_b)/carbon_vulnerable_b) %>%
  dplyr::select(`Species Richness`:`CRENVU Richness`, carbon_vulnerable, Category) %>%
  pivot_longer(-Category) %>%
  mutate(type = Category) %>%
  mutate(Category = plyr::revalue(Category, c(Private = "easement", Public = "fee") ))
```

```{r}
public_private <- public_private %>%
  filter(name != "carbon_vulnerable")
```


## With Lawler Data

```{r}
f2e <- easements %>%
  group_by(Category) %>%
  mutate(total_area = sum(area)) %>%
  ungroup() %>%
  mutate(perc_area = area/total_area) %>%
  mutate(reptiles = reptile_future*perc_area,
         amphibians = amphibian_future*perc_area,
         mammals= mammal_future*perc_area,
         birds = bird_future*perc_area,
         trees = tree_future*perc_area,
         plants = plant_future*perc_area) %>%
  group_by(Category) %>%
  summarise(reptiles = sum(reptiles, na.rm = TRUE),
         amphibians = sum(amphibians, na.rm = TRUE),
         mammals= sum(mammals, na.rm = TRUE),
         birds = sum(birds, na.rm = TRUE),
         trees = sum(trees, na.rm = TRUE),
         plants = sum(plants, na.rm = TRUE))
```

```{r}
f2f <- fee %>%
  filter(GAP_Sts == 1 | GAP_Sts == 2) %>%
  group_by(Category) %>%
  mutate(total_area = sum(area)) %>%
  ungroup() %>%
  mutate(perc_area = area/total_area) %>%
  mutate(reptiles = reptile_future*perc_area,
         amphibians = amphibian_future*perc_area,
         mammals= mammal_future*perc_area,
         birds = bird_future*perc_area,
         trees = tree_future*perc_area,
         plants = plant_future*perc_area) %>%
  group_by(Category) %>%
  summarise(reptiles = sum(reptiles, na.rm = TRUE),
         amphibians = sum(amphibians, na.rm = TRUE),
         mammals= sum(mammals, na.rm = TRUE),
         birds = sum(birds, na.rm = TRUE),
         trees = sum(trees, na.rm = TRUE),
         plants = sum(plants, na.rm = TRUE))
```

```{r}
f2e %>%
  rbind(f2f)
```


```{r}
f2public <- fee %>%
  dplyr::select(-Category) %>%
  mutate(Category = "Public") %>%
  group_by(Category) %>%
  mutate(total_area_public = sum(area)) %>%
  ungroup() %>%
  mutate(perc_area = area/total_area_public) %>%
  mutate(reptiles = reptile_future*perc_area,
         amphibians = amphibian_future*perc_area,
         mammals= mammal_future*perc_area,
         birds = bird_future*perc_area,
         trees = tree_future*perc_area,
         plants = plant_future*perc_area) %>%
  group_by(Category,total_area_public) %>%
  summarise(reptiles = sum(reptiles, na.rm = TRUE),
         amphibians = sum(amphibians, na.rm = TRUE),
         mammals= sum(mammals, na.rm = TRUE),
         birds = sum(birds, na.rm = TRUE),
         trees = sum(trees, na.rm = TRUE),
         plants = sum(plants, na.rm = TRUE)) %>% ungroup() %>%
  mutate(aggregate = reptiles + amphibians + mammals + birds + trees + plants)
```

```{r}
f2background <- background %>%
  mutate(Category = "background") %>%
  group_by(Category) %>%
  mutate(total_area_ca = sum(area)) %>%
  ungroup() %>%
  mutate(perc_area = area/total_area_ca) %>%
   mutate(reptiles = reptile_future*perc_area,
         amphibians = amphibian_future*perc_area,
         mammals= mammal_future*perc_area,
         birds = bird_future*perc_area,
         trees = tree_future*perc_area,
         plants = plant_future*perc_area) %>%
  group_by(Category, total_area_ca) %>%
  summarise(reptiles_b = sum(reptiles, na.rm = TRUE),
         amphibians_b = sum(amphibians, na.rm = TRUE),
         mammals_b= sum(mammals, na.rm = TRUE),
         birds_b = sum(birds, na.rm = TRUE),
         trees_b = sum(trees, na.rm = TRUE),
         plants_b = sum(plants, na.rm = TRUE)) %>%
  ungroup() %>%
  mutate(aggregate_b = reptiles_b + amphibians_b + mammals_b + birds_b + trees_b + plants_b) %>%
  dplyr::select(-Category) %>%
  mutate(bind = "a")
```

```{r}
f2private <- f2public %>%
  dplyr::select(-Category) %>%
  cbind(f2background) %>%
  mutate(area_private = total_area_ca-total_area_public) %>%
  mutate(reptiles = ((reptiles_b*total_area_ca)-(reptiles*total_area_public))/(area_private),
         amphibians = ((amphibians_b*total_area_ca)-(amphibians*total_area_public))/(area_private),
         mammals = ((mammals_b*total_area_ca)-(mammals*total_area_public))/(area_private),
         birds = ((birds_b*total_area_ca)-(birds*total_area_public))/(area_private),
         trees = ((trees_b*total_area_ca)-(trees*total_area_public))/(area_private),
         plants = ((plants_b*total_area_ca)-(plants*total_area_public))/(area_private),
         aggregate = ((aggregate_b*total_area_ca)-(aggregate*total_area_public))/(area_private)) %>%
  dplyr::select(reptiles:plants, aggregate, area_private) %>%
  mutate(Category = "Private") %>%
  rename(area = area_private)
```

public private

```{r}
public_private <- f2public %>%
  rename(area = total_area_public) %>%
  rbind(f2private) %>%
  mutate(bind= "a") %>%
  full_join(f2background) %>%
  dplyr::mutate(reptiles = (reptiles-reptiles_b)/reptiles_b,
                amphibians = (amphibians-amphibians_b)/amphibians_b,
                mammals =(mammals-mammals_b)/mammals_b,
                birds = (birds-birds_b)/birds_b,
                trees = (trees-trees_b)/trees_b,
                plants = (plants-plants_b)/plants_b,
                `aggregate \n richness` = (aggregate-aggregate_b)/aggregate_b)%>%
  dplyr::select(reptiles:plants, Category) %>%
  pivot_longer(-Category) %>%
  mutate(type = Category) %>%
  mutate(Category = recode(type, Private = "conservation easement", Public = "protected area"))
```

```{r future, fig.width= 4 , fig.height=4, dpi = 300}
fig5a <- f2e %>%
  rbind(f2f) %>%
  mutate(bind = "a") %>%
  mutate(aggregate = reptiles + amphibians + mammals + birds + trees + plants) %>%
  full_join(f2background) %>%
  dplyr::select(-c(bind, total_area_ca)) %>%
  dplyr::mutate(reptiles = (reptiles-reptiles_b)/reptiles_b,
                amphibians = (amphibians-amphibians_b)/amphibians_b,
                mammals =(mammals-mammals_b)/mammals_b,
                birds = (birds-birds_b)/birds_b,
                trees = (trees-trees_b)/trees_b,
                plants = (plants-plants_b)/plants_b,
                `aggregate \n richness` = (aggregate-aggregate_b)/aggregate_b) %>%
  dplyr::select(Category,reptiles:plants) %>%
  pivot_longer(-Category) %>%
  mutate(Category = recode(Category, easement = "conservation easement", fee = "protected area")) %>%
  ggplot(aes(x = name, y = value*100, fill = Category)) + 
  geom_bar(stat = "identity", width=0.65,
                                  position=position_dodge(width=0.8)) +
    scale_fill_manual(values=c("#0072B2", "#E69F00", "black")) +
  geom_point(public_private, mapping = aes(x = name, y= as.numeric(value)*100,  
                                           group = type, 
                                           shape= type), stat = "identity", 
             position=position_dodge(width=0.8), size = 3) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  theme_classic() +
  theme(axis.title.y =element_blank()) +
  theme(axis.text.y = element_text(angle = 90,hjust=0.5)) +
  theme(legend.title = element_blank()) + coord_flip() +
  theme(legend.position = "bottom") +
  ylim(-75,75) +
   theme(axis.text=element_text(size=8),
        axis.title=element_text(size=10),
        panel.border = element_rect(colour = "black", fill=NA),
        legend.box.background = element_rect(colour = "black"),
        legend.text = element_text(size = 8)) +
  guides(shape = guide_legend(override.aes = list(size = 3))) +
    labs(y = "% difference from national mean \n future species richness (Year 2100, RCP 8.5)") 
fig5a
```


## With IUCN Data

```{r}
f2e <- easements %>%
  group_by(Category) %>%
  mutate(total_area = sum(area)) %>%
  ungroup() %>%
  dplyr::select(-c(Own_Type, Mang_Type, Src_Date)) %>%
  drop_na() %>%
  mutate(perc_area = area/total_area) %>%
  mutate(reptiles = replace_na(reptile_iucn, 0)*perc_area,
         amphibians = replace_na(amphibian_iucn,0)*perc_area,
         mammals= replace_na(mammal_iucn,0)*perc_area,
         birds = replace_na(bird_iucn,0)*perc_area,
         fish = replace_na(fw_iucn,0)*perc_area) %>%
  group_by(Category) %>%
  summarise(reptiles = sum(reptiles,na.rm = TRUE),
         amphibians = sum(amphibians, na.rm = TRUE),
         mammals= sum(mammals, na.rm = TRUE),
         birds = sum(birds, na.rm = TRUE),
         fish = sum(fish, na.rm = TRUE))
```

```{r}
f2f <- fee %>%
  filter(GAP_Sts == 1 | GAP_Sts == 2) %>%
  group_by(Category) %>%
  mutate(total_area = sum(area)) %>%
  ungroup() %>%
  dplyr::select(-c(Own_Type, Mang_Type, Date_Est)) %>%
  drop_na() %>%
  mutate(perc_area = area/total_area) %>%
  mutate(reptiles = replace_na(reptile_iucn, 0)*perc_area,
         amphibians = replace_na(amphibian_iucn,0)*perc_area,
         mammals= replace_na(mammal_iucn,0)*perc_area,
         birds = replace_na(bird_iucn,0)*perc_area,
         fish = replace_na(fw_iucn,0)*perc_area) %>%
  group_by(Category) %>%
  summarise(reptiles = sum(reptiles,na.rm = TRUE),
         amphibians = sum(amphibians, na.rm = TRUE),
         mammals= sum(mammals, na.rm = TRUE),
         birds = sum(birds, na.rm = TRUE),
         fish = sum(fish, na.rm = TRUE)) %>%
  filter(Category == "Fee")
```


background, public, private

```{r}
f2public <- fee %>%
  filter(Category == "Fee") %>%
  mutate(Category = recode(Category, Fee = "Public")) %>%
  group_by(Category) %>%
  mutate(total_area = sum(area)) %>%
  ungroup() %>%
  dplyr::select(-c(Own_Type, Mang_Type, Date_Est)) %>%
  drop_na() %>%
  mutate(perc_area = area/total_area) %>%
  mutate(reptiles = replace_na(reptile_iucn, 0)*perc_area,
         amphibians = replace_na(amphibian_iucn,0)*perc_area,
         mammals= replace_na(mammal_iucn,0)*perc_area,
         birds = replace_na(bird_iucn,0)*perc_area,
         fish = replace_na(fw_iucn,0)*perc_area) %>%
  group_by(Category) %>%
  summarise(reptiles = sum(reptiles,na.rm = TRUE),
         amphibians = sum(amphibians, na.rm = TRUE),
         mammals= sum(mammals, na.rm = TRUE),
         birds = sum(birds, na.rm = TRUE),
         fish = sum(fish, na.rm = TRUE),
         area = sum(area))
```

```{r}
f2background <- background %>%
  mutate(Category = "background") %>%
  group_by(Category) %>%
  mutate(total_area = sum(area)) %>%
  ungroup() %>%
  mutate(perc_area = area/total_area) %>%
  mutate(reptiles_b = replace_na(reptile_iucn, 0)*perc_area,
         amphibians_b = replace_na(amphibian_iucn,0)*perc_area,
         mammals_b = replace_na(mammal_iucn,0)*perc_area,
         birds_b = replace_na(bird_iucn,0)*perc_area,
         fish_b = replace_na(fw_iucn,0)*perc_area) %>%
  group_by(Category) %>%
  summarise(reptiles_b = sum(reptiles_b),
         amphibians_b = sum(amphibians_b),
         mammals_b = sum(mammals_b),
         birds_b = sum(birds_b),
         fish_b = sum(fish_b),
         area_b = mean(total_area)) %>%
  dplyr::select(-Category) %>%
  mutate(richness = "richness")
```

```{r}
f2private <- f2public %>%
  dplyr::select(-Category) %>%
  cbind(f2background) %>%
  mutate(area_p = area_b-area) %>%
  mutate(reptiles = ((reptiles_b*area_b/area_b)-(reptiles*area/area_b))/(area_p/area_b),
         amphibians = ((amphibians_b*area_b/area_b)-(amphibians*area/area_b))/(area_p/area_b),
         mammals = ((mammals_b*area_b/area_b)-(mammals*area/area_b))/(area_p/area_b),
         birds = ((birds_b*area_b/area_b)-(birds*area/area_b))/(area_p/area_b),
         fish = ((fish_b*area_b/area_b)-(fish*area/area_b))/(area_p/area_b)) %>%
  dplyr::select(reptiles:fish, area_p) %>%
  mutate(Category = "Private") %>%
  rename(area = area_p)
```

public private

```{r}
public_private <- f2private %>% rbind(f2public) %>%
  mutate(richness = "richness") %>%
  full_join(f2background) %>%
  mutate(reptiles = (reptiles-reptiles_b)/reptiles_b*100,
         amphibians = (amphibians-amphibians_b)/amphibians_b*100,
         mammals = (mammals-mammals_b)/mammals_b*100,
         birds = (birds-birds_b)/birds_b*100,
         fish = (fish-fish_b)/fish_b*100) %>%
  dplyr::select(reptiles:fish, Category) %>%
  pivot_longer(-Category)
```

```{r}
fee_easement <- f2f %>% rbind(f2e) %>%
  mutate(richness = "richness") %>%
  full_join(f2background) %>%
  mutate(reptiles = (reptiles-reptiles_b)/reptiles_b*100,
         amphibians = (amphibians-amphibians_b)/amphibians_b*100,
         mammals = (mammals-mammals_b)/mammals_b*100,
         birds = (birds-birds_b)/birds_b*100,
         fish = (fish-fish_b)/fish_b*100) %>%
  dplyr::select(Category:fish) %>%
  pivot_longer(-Category)
```

```{r fig.width=5, fig.height=5, dpi = 300}
ggplot() + 
  scale_fill_manual(values=c("#0072B2", "#E69F00")) +
  geom_bar(fee_easement, mapping = aes(x= name, y= as.numeric(value), fill = Category),
                                  stat = "identity", width=0.65,
                                  position=position_dodge(width=0.8)) +
  geom_hline(yintercept=0, linetype="dashed") +
  #geom_point(richness_background, mapping = aes(x = name, y= value), pch = 19) +
  geom_point(public_private, mapping = aes(x = name, y= as.numeric(value),  
                                           group = Category, color = Category, 
                                           shape= Category), stat = "identity", 
             position=position_dodge(width=0.8), size = 3) +
  scale_color_manual(values=c("black", "black")) +
  scale_shape_manual(values=c(20,18)) +
  theme_classic() +
  theme(axis.title.y =element_blank()) +
  theme(axis.text.y = element_text(angle = 90,hjust=0.5)) +
  theme(legend.title = element_blank()) + coord_flip() +
  theme(legend.position = "bottom") +
  ylim(-95,95) +
   theme(axis.text=element_text(size=8),
        axis.title=element_text(size=10),
        panel.border = element_rect(colour = "black", fill=NA),
        legend.box.background = element_rect(colour = "black"),
        legend.text = element_text(size = 8)) +
  guides(shape = guide_legend(override.aes = list(size = 5))) +
    labs(y = "% difference from background mean species richness") 
```



## By year 

```{r}
f2e <- easements %>%
  group_by(Category) %>%
  mutate(total_area = sum(area)) %>%
  ungroup() %>%
  dplyr::select(-c(Own_Type, Mang_Type, Src_Date)) %>%
  drop_na() %>%
  mutate(perc_area = area/total_area) %>%
  mutate(reptiles = replace_na(reptile_iucn, 0)*perc_area,
         amphibians = replace_na(amphibian_iucn,0)*perc_area,
         mammals= replace_na(mammal_iucn,0)*perc_area,
         birds = replace_na(bird_iucn,0)*perc_area,
         fish = replace_na(fw_iucn,0)*perc_area) %>%
  group_by(Category) %>%
  summarise(reptiles = sum(reptiles,na.rm = TRUE),
         amphibians = sum(amphibians, na.rm = TRUE),
         mammals= sum(mammals, na.rm = TRUE),
         birds = sum(birds, na.rm = TRUE),
         fish = sum(fish, na.rm = TRUE))
```


## By State

```{r}
f2e <- easements %>%
  group_by(Category, State_Nm) %>%
  mutate(total_area = sum(area)) %>%
  ungroup() %>% 
  mutate(perc_area = area/total_area) %>%
  mutate(reptiles = replace_na(reptile_iucn, 0)*perc_area,
         amphibians = replace_na(amphibian_iucn,0)*perc_area,
         mammals= replace_na(mammal_iucn,0)*perc_area,
         birds = replace_na(bird_iucn,0)*perc_area,
         fish = replace_na(fw_iucn,0)*perc_area) %>%
  group_by(Category, State_Nm) %>%
  summarise(reptiles = sum(reptiles,na.rm = TRUE),
         amphibians = sum(amphibians, na.rm = TRUE),
         mammals= sum(mammals, na.rm = TRUE),
         birds = sum(birds, na.rm = TRUE),
         fish = sum(fish, na.rm = TRUE))
```

```{r}
f2f <- fee %>%
  filter(GAP_Sts == 1 | GAP_Sts == 2) %>%
  group_by(Category, State_Nm) %>%
  mutate(total_area = sum(area)) %>%
  ungroup() %>% 
  mutate(perc_area = area/total_area) %>%
  mutate(reptiles = replace_na(reptile_iucn, 0)*perc_area,
         amphibians = replace_na(amphibian_iucn,0)*perc_area,
         mammals= replace_na(mammal_iucn,0)*perc_area,
         birds = replace_na(bird_iucn,0)*perc_area,
         fish = replace_na(fw_iucn,0)*perc_area) %>%
  group_by(Category, State_Nm) %>%
  summarise(reptiles = sum(reptiles,na.rm = TRUE),
         amphibians = sum(amphibians, na.rm = TRUE),
         mammals= sum(mammals, na.rm = TRUE),
         birds = sum(birds, na.rm = TRUE),
         fish = sum(fish, na.rm = TRUE)) %>%
  filter(Category == "Fee")
```

```{r}
f2public <- fee %>%
  filter(Category == "Fee") %>%
  mutate(Category = recode(Category, Fee = "Public")) %>%
  group_by(Category, State_Nm) %>%
  mutate(total_area = sum(area)) %>%
  ungroup() %>%
  mutate(perc_area = area/total_area) %>%
  mutate(reptiles = replace_na(reptile_iucn, 0)*perc_area,
         amphibians = replace_na(amphibian_iucn,0)*perc_area,
         mammals= replace_na(mammal_iucn,0)*perc_area,
         birds = replace_na(bird_iucn,0)*perc_area,
         fish = replace_na(fw_iucn,0)*perc_area)  %>%
  group_by(Category, State_Nm) %>%
  summarise(reptiles = sum(reptiles),
         amphibians = sum(amphibians),
         mammals= sum(mammals),
         birds = sum(birds),
         fish = sum(fish),
         area = sum(area))
```

```{r}
f2background <- background %>%
  rename(State_Nm = STATE) %>%
  mutate(Category = "background") %>%
  group_by(Category, State_Nm) %>%
  mutate(total_area = sum(area)) %>%
  ungroup() %>%
  mutate(perc_area = area/total_area) %>%
 mutate(reptiles_b = replace_na(reptile_iucn, 0)*perc_area,
         amphibians_b = replace_na(amphibian_iucn,0)*perc_area,
         mammals_b = replace_na(mammal_iucn,0)*perc_area,
         birds_b = replace_na(bird_iucn,0)*perc_area,
         fish_b = replace_na(fw_iucn,0)*perc_area) %>%
  group_by(Category, State_Nm) %>%
  summarise(reptiles_b = sum(reptiles_b),
         amphibians_b = sum(amphibians_b),
         mammals_b = sum(mammals_b),
         birds_b = sum(birds_b),
         fish_b = sum(fish_b),
         area_b = mean(total_area)) %>%
  dplyr::select(-Category) %>%
  mutate(richness = "richness")
```

```{r}
f2private <- f2public %>%
  dplyr::select(-Category) %>%
  left_join(f2background, by = "State_Nm") %>%
  mutate(area_p = area_b-area) %>%
  mutate(reptiles = ((reptiles_b*area_b/area_b)-(reptiles*area/area_b))/(area_p/area_b),
         amphibians = ((amphibians_b*area_b/area_b)-(amphibians*area/area_b))/(area_p/area_b),
         mammals = ((mammals_b*area_b/area_b)-(mammals*area/area_b))/(area_p/area_b),
         birds = ((birds_b*area_b/area_b)-(birds*area/area_b))/(area_p/area_b),
         fish = ((fish_b*area_b/area_b)-(fish*area/area_b))/(area_p/area_b)) %>%
  dplyr::select(reptiles:fish, area_p) %>%
  mutate(Category = "Private") %>%
  rename(area = area_p)
```

public private

```{r}
public_private <- f2private %>% rbind(f2public) %>%
  mutate(richness = "richness") %>%
  left_join(f2background, by = "State_Nm") %>%
  mutate(reptiles = (reptiles-reptiles_b)/reptiles_b*100,
         amphibians = (amphibians-amphibians_b)/amphibians_b*100,
         mammals = (mammals-mammals_b)/mammals_b*100,
         birds = (birds-birds_b)/birds_b*100,
         fish = (fish-fish_b)/fish_b*100) %>%
  dplyr::select(reptiles:fish, Category) %>%
  pivot_longer(-Category)
```

```{r}
fee_easement <- f2f %>% rbind(f2e) %>%
  full_join(f2background, by = "State_Nm") %>%
  mutate(reptiles = (reptiles-reptiles_b)/reptiles_b*100,
         amphibians = (amphibians-amphibians_b)/amphibians_b*100,
         mammals = (mammals-mammals_b)/mammals_b*100,
         birds = (birds-birds_b)/birds_b*100,
         fish = (fish-fish_b)/fish_b*100) %>%
  dplyr::select(Category.x:fish) %>%
  pivot_longer(-c(Category.x, State_Nm))
```
