---
title: "richness_maps"
output: html_document
---


```{r}
library(sf)
library(tidyverse)
library(raster)
```

# from Lawler current

amphibians

```{r}
#first import all files in a single folder as a list 
path_a <- "../data/SpeciesProjections/SpeciesProjections/Historical/Amphibians/"
amphibians <- list.files(path = path_a, pattern='.tif$', all.files=TRUE, full.names=FALSE)

amphibian_richness <- raster(paste0(path_a, amphibians[1]))
for (i in 2:length(amphibians)) {
  spp <- raster(paste0(path_a, amphibians[i]))
  amphibians_stack <- stack(amphibian_richness, spp)
  amphibian_richness <- calc(amphibians_stack, sum)
}
rm(amphibians_stack, spp, amphibians, path_a)
writeRaster(amphibian_richness, "../data/richness_rasters/amphibian_richness_lawler.tif", overwrite = TRUE)
amphibian_richness <- raster("../data/richness_rasters/amphibian_richness_lawler.tif")
plot(amphibian_richness)
```

birds

```{r}
#first import all files in a single folder as a list 
path_b <- "../data/SpeciesProjections/SpeciesProjections/Historical/Birds/"
birds <- list.files(path = path_b, pattern='.tif$', all.files=TRUE, full.names=FALSE)

birds_richness <- raster(paste0(path_b, birds[1]))
for (i in 2:length(birds)) {
  spp <- raster(paste0(path_b, birds[i]))
  birds_stack <- stack(birds_richness, spp)
  birds_richness <- calc(birds_stack, sum)
}
rm(birds_stack, spp, birds, path_b)
writeRaster(birds_richness, "../data/richness_rasters/bird_richness_lawler.tif")
birds_richness <- raster("../data/richness_rasters/bird_richness_lawler.tif")
plot(birds_richness)
```

plants

```{r}
#first import all files in a single folder as a list 
path_p <- "../data/SpeciesProjections/SpeciesProjections/Historical/Plants/"
plants <- list.files(path = path_p, pattern='.tif$', all.files=TRUE, full.names=FALSE)

plants_richness <- raster(paste0(path_p, plants[1]))
for (i in 2:length(plants)) {
  spp <- raster(paste0(path_p, plants[i]))
  plants_stack <- stack(plants_richness, spp)
  plants_richness <- calc(plants_stack, sum)
  print(i)
}
rm(plants_stack, spp, plants, path_p)
writeRaster(plants_richness, "../data/richness_rasters/plant_richness_lawler.tif")
plant_richness <- raster("../data/richness_rasters/plant_richness_lawler.tif")
plot(plant_richness)
```

mammals

```{r}
#first import all files in a single folder as a list 
path_m <- "../data/SpeciesProjections/SpeciesProjections/Historical/Mammals/"
mammals <- list.files(path = path_m, pattern='.tif$', all.files=TRUE, full.names=FALSE)

mammals_richness <- raster(paste0(path_m, mammals[1]))
for (i in 2:length(mammals)) {
  spp <- raster(paste0(path_m, mammals[i]))
  mammals_stack <- stack(mammals_richness, spp)
  mammals_richness <- calc(mammals_stack, sum)
  print(i)
}
rm(mammals_stack, spp, mammals, path_m)
writeRaster(mammals_richness, "../data/richness_rasters/mammal_richness_lawler.tif", overwrite=TRUE)
mammals_richness <- raster("../data/richness_rasters/mammal_richness_lawler.tif")
plot(mammals_richness)
```

trees

```{r}
#first import all files in a single folder as a list 
path_t <- "../data/SpeciesProjections/SpeciesProjections/Historical/Trees/"
tree <- list.files(path = path_t, pattern='.tif$', all.files=TRUE, full.names=FALSE)

tree_richness <- raster(paste0(path_t, tree[1]))
for (i in 2:length(tree)) {
  spp <- raster(paste0(path_t, tree[i]))
  tree_stack <- stack(tree_richness, spp)
  tree_richness <- calc(tree_stack, sum)
  print(i)
}
rm(tree_stack, spp, tree, path_t)
writeRaster(tree_richness, "../data/richness_rasters/tree_richness_lawler.tif")
tree_richness <- raster("../data/richness_rasters/tree_richness_lawler.tif")
plot(tree_richness)
```

reptiles

```{r}
#first import all files in a single folder as a list 
path_r <- "../data/SpeciesProjections/SpeciesProjections/Historical/Reptiles/"
reptiles <- list.files(path = path_r, pattern='.tif$', all.files=TRUE, full.names=FALSE)

reptile_richness <- raster(paste0(path_r, reptiles[1]))
for (i in 2:length(reptiles)) {
  spp <- raster(paste0(path_r, reptiles[i]))
  reptiles_stack <- stack(reptile_richness, spp)
  reptile_richness <- calc(reptiles_stack, sum)
  print(i)
}
rm(reptile_stack, spp, reptiles, path_p)
writeRaster(reptile_richness, "../data/richness_rasters/reptile_richness_lawler.tif")
reptile_richness <- raster("../data/richness_rasters/reptile_richness_lawler.tif")
plot(reptile_richness)
```




# Lawler Future

## trees

```{r warning = FALSE}
#first import all files in a single folder as a list 
path_t <- "../data/SpeciesProjections/SpeciesProjections/Future/gf85bi70/Trees/"
tree <- list.files(path = path_t, pattern='.tif$', all.files=TRUE, full.names=FALSE)

tree_richness <- raster(paste0(path_t, tree[1]))
for (i in 2:length(tree)) {
  spp <- raster(paste0(path_t, tree[i]))
  tree_stack <- stack(tree_richness, spp)
  tree_richness <- calc(tree_stack, sum)
  print(i)
}
tree_gf <- tree_richness
rm(tree_stack, spp, tree, path_t, tree_richness)

#first import all files in a single folder as a list 
path_t <- "../data/SpeciesProjections/SpeciesProjections/Future/in85bi70/Trees/"
tree <- list.files(path = path_t, pattern='.tif$', all.files=TRUE, full.names=FALSE)

tree_richness <- raster(paste0(path_t, tree[1]))
for (i in 2:length(tree)) {
  spp <- raster(paste0(path_t, tree[i]))
  tree_stack <- stack(tree_richness, spp)
  tree_richness <- calc(tree_stack, sum)
  print(i)
}
tree_in <- tree_richness
rm(tree_stack, spp, tree, path_t, tree_richness)

path_t <- "../data/SpeciesProjections/SpeciesProjections/Future/mc85bi70/Trees/"
tree <- list.files(path = path_t, pattern='.tif$', all.files=TRUE, full.names=FALSE)

tree_richness <- raster(paste0(path_t, tree[1]))
for (i in 2:length(tree)) {
  spp <- raster(paste0(path_t, tree[i]))
  tree_stack <- stack(tree_richness, spp)
  tree_richness <- calc(tree_stack, sum)
  print(i)
}
tree_mc <- tree_richness
rm(tree_stack, spp, tree, path_t, tree_richness)
```

```{r}
trees <- stack(tree_mc, tree_in, tree_gf)
tree_future <- calc(trees, mean)
writeRaster(tree_future, "../data/richness_rasters/tree_future_lawler.tif")
tree_richness <- raster("../data/richness_rasters/tree_future_lawler.tif")
plot(tree_richness)
```


## mammals

```{r warning=FALSE}
#first import all files in a single folder as a list 
path_m <- "../data/SpeciesProjections/SpeciesProjections/Future/gf85bi70/Mammals/"
mammals <- list.files(path = path_m, pattern='.tif$', all.files=TRUE, full.names=FALSE)

mammals_richness <- raster(paste0(path_m, mammals[1]))
for (i in 2:length(mammals)) {
  spp <- raster(paste0(path_m, mammals[i]))
  mammals_stack <- stack(mammals_richness, spp)
  mammals_richness <- calc(mammals_stack, sum)
  print(i)
}
mammal_gf <- mammals_richness
rm(mammals_stack, spp, mammal, path_m, mammals_richness)

#first import all files in a single folder as a list 
path_m <- "../data/SpeciesProjections/SpeciesProjections/Future/in85bi70/Mammals/"
mammals <- list.files(path = path_m, pattern='.tif$', all.files=TRUE, full.names=FALSE)

mammals_richness <- raster(paste0(path_m, mammals[1]))
for (i in 2:length(mammals)) {
  spp <- raster(paste0(path_m, mammals[i]))
  mammals_stack <- stack(mammals_richness, spp)
  mammals_richness <- calc(mammals_stack, sum)
  print(i)
}
mammal_in <- mammals_richness
rm(mammals_stack, spp, mammal, path_m, mammals_richness)

#first import all files in a single folder as a list 
path_m <- "../data/SpeciesProjections/SpeciesProjections/Future/mc85bi70/Mammals/"
mammals <- list.files(path = path_m, pattern='.tif$', all.files=TRUE, full.names=FALSE)

mammals_richness <- raster(paste0(path_m, mammals[1]))
for (i in 2:length(mammals)) {
  spp <- raster(paste0(path_m, mammals[i]))
  mammals_stack <- stack(mammals_richness, spp)
  mammals_richness <- calc(mammals_stack, sum)
  print(i)
}
mammal_mc <- mammals_richness
rm(mammals_stack, spp, mammal, path_m, mammals_richness)
```

```{r}
mammals <- stack(mammal_mc, mammal_in, mammal_gf)
mammal_future <- calc(mammals, mean)
writeRaster(mammal_future, "../data/richness_rasters/mammal_future_lawler.tif")
```


## reptiles

```{r warning=FALSE}
#first import all files in a single folder as a list 
path_r <- "../data/SpeciesProjections/SpeciesProjections/Future/gf85bi70/Reptiles/"
reptiles <- list.files(path = path_r, pattern='.tif$', all.files=TRUE, full.names=FALSE)

reptile_richness <- raster(paste0(path_r, reptiles[1]))
for (i in 2:length(reptiles)) {
  spp <- raster(paste0(path_r, reptiles[i]))
  reptiles_stack <- stack(reptile_richness, spp)
  reptile_richness <- calc(reptiles_stack, sum)
  print(i)
}
reptile_gf <- reptile_richness
rm(reptiles_stack, spp, reptiles, path_r, reptile_richness)

#first import all files in a single folder as a list 
path_r <- "../data/SpeciesProjections/SpeciesProjections/Future/mc85bi70/Reptiles/"
reptiles <- list.files(path = path_r, pattern='.tif$', all.files=TRUE, full.names=FALSE)

reptile_richness <- raster(paste0(path_r, reptiles[1]))
for (i in 2:length(reptiles)) {
  spp <- raster(paste0(path_r, reptiles[i]))
  reptiles_stack <- stack(reptile_richness, spp)
  reptile_richness <- calc(reptiles_stack, sum)
  print(i)
}
reptile_mc <- reptile_richness
rm(reptiles_stack, spp, reptiles, path_r, reptile_richness)

#first import all files in a single folder as a list 
path_r <- "../data/SpeciesProjections/SpeciesProjections/Future/in85bi70/Reptiles/"
reptiles <- list.files(path = path_r, pattern='.tif$', all.files=TRUE, full.names=FALSE)

reptile_richness <- raster(paste0(path_r, reptiles[1]))
for (i in 2:length(reptiles)) {
  spp <- raster(paste0(path_r, reptiles[i]))
  reptiles_stack <- stack(reptile_richness, spp)
  reptile_richness <- calc(reptiles_stack, sum)
  print(i)
}
reptile_in <- reptile_richness
rm(reptiles_stack, spp, reptiles, path_r, reptile_richness)
```

```{r}
reptiles <- stack(reptile_in, reptile_mc, reptile_gf)
reptiles_future <- calc(reptiles, mean)
writeRaster(reptiles_future, "../data/richness_rasters/reptile_future_lawler.tif")
```


## plants

```{r warning=FALSE}
#first import all files in a single folder as a list 
path_p <- "../data/SpeciesProjections/SpeciesProjections/Future/gf85bi70/Plants/"
plants <- list.files(path = path_p, pattern='.tif$', all.files=TRUE, full.names=FALSE)

plants_richness <- raster(paste0(path_p, plants[1]))
for (i in 2:length(plants)) {
  spp <- raster(paste0(path_p, plants[i]))
  plants_stack <- stack(plants_richness, spp)
  plants_richness <- calc(plants_stack, sum)
  print(i)
}
plant_gf <- plants_richness
rm(plants_stack, spp, plants, path_p, plants_richness)

#first import all files in a single folder as a list 
path_p <- "../data/SpeciesProjections/SpeciesProjections/Future/in85bi70/Plants/"
plants <- list.files(path = path_p, pattern='.tif$', all.files=TRUE, full.names=FALSE)

plants_richness <- raster(paste0(path_p, plants[1]))
for (i in 2:length(plants)) {
  spp <- raster(paste0(path_p, plants[i]))
  plants_stack <- stack(plants_richness, spp)
  plants_richness <- calc(plants_stack, sum)
  print(i)
}
plant_in <- plants_richness
rm(plants_stack, spp, plants, path_p, plants_richness)

#first import all files in a single folder as a list 
path_p <- "../data/SpeciesProjections/SpeciesProjections/Future/mc85bi70/Plants/"
plants <- list.files(path = path_p, pattern='.tif$', all.files=TRUE, full.names=FALSE)

plants_richness <- raster(paste0(path_p, plants[1]))
for (i in 2:length(plants)) {
  spp <- raster(paste0(path_p, plants[i]))
  plants_stack <- stack(plants_richness, spp)
  plants_richness <- calc(plants_stack, sum)
  print(i)
}
plant_mc <- plants_richness
rm(plants_stack, spp, plants, path_p, plants_richness)
```


```{r}
plants <- stack(plant_mc, plant_in, plant_gf)
plants_future <- calc(plants, mean)
writeRaster(plants_future, "../data/richness_rasters/plants_future_lawler.tif")
```


## birds

```{r warning = FALSE}
#first import all files in a single folder as a list 
path_b <- "../data/SpeciesProjections/SpeciesProjections/Future/gf85bi70/Birds/"
birds <- list.files(path = path_b, pattern='.tif$', all.files=TRUE, full.names=FALSE)

birds_richness <- raster(paste0(path_b, birds[1]))
for (i in 2:length(birds)) {
  spp <- raster(paste0(path_b, birds[i]))
  birds_stack <- stack(birds_richness, spp)
  birds_richness <- calc(birds_stack, sum)
}
birds_gf <- birds_richness
rm(birds_stack, spp, birds, path_b, birds_richness)

#first import all files in a single folder as a list 
path_b <- "../data/SpeciesProjections/SpeciesProjections/Future/in85bi70/Birds/"
birds <- list.files(path = path_b, pattern='.tif$', all.files=TRUE, full.names=FALSE)

birds_richness <- raster(paste0(path_b, birds[1]))
for (i in 2:length(birds)) {
  spp <- raster(paste0(path_b, birds[i]))
  birds_stack <- stack(birds_richness, spp)
  birds_richness <- calc(birds_stack, sum)
}
birds_in <- birds_richness
rm(birds_stack, spp, birds, path_b, birds_richness)

#first import all files in a single folder as a list 
path_b <- "../data/SpeciesProjections/SpeciesProjections/Future/mc85bi70/Birds/"
birds <- list.files(path = path_b, pattern='.tif$', all.files=TRUE, full.names=FALSE)

birds_richness <- raster(paste0(path_b, birds[1]))
for (i in 2:length(birds)) {
  spp <- raster(paste0(path_b, birds[i]))
  birds_stack <- stack(birds_richness, spp)
  birds_richness <- calc(birds_stack, sum)
}
birds_mc <- birds_richness
rm(birds_stack, spp, birds, path_b, birds_richness)
```

```{r}
birds <- stack(birds_mc, birds_in, birds_gf)
birds_future <- calc(birds, mean)
writeRaster(birds_future, "../data/richness_rasters/birds_future_lawler.tif")
```


## amphibians

```{r warning=FALSE}
#first import all files in a single folder as a list 
path_a <- "../data/SpeciesProjections/SpeciesProjections/Future/gf85bi70/Amphibians/"
amphibians <- list.files(path = path_a, pattern='.tif$', all.files=TRUE, full.names=FALSE)

amphibian_richness <- raster(paste0(path_a, amphibians[1]))
for (i in 2:length(amphibians)) {
  spp <- raster(paste0(path_a, amphibians[i]))
  amphibians_stack <- stack(amphibian_richness, spp)
  amphibian_richness <- calc(amphibians_stack, sum)
}
amphibian_gf <- amphibian_richness
rm(amphibians_stack, spp, tree, path_a, amphibian_richness)

#first import all files in a single folder as a list 
path_a <- "../data/SpeciesProjections/SpeciesProjections/Future/in85bi70/Amphibians/"
amphibians <- list.files(path = path_a, pattern='.tif$', all.files=TRUE, full.names=FALSE)

amphibian_richness <- raster(paste0(path_a, amphibians[1]))
for (i in 2:length(amphibians)) {
  spp <- raster(paste0(path_a, amphibians[i]))
  amphibians_stack <- stack(amphibian_richness, spp)
  amphibian_richness <- calc(amphibians_stack, sum)
}
amphibian_in <- amphibian_richness
rm(amphibians_stack, spp, tree, path_a, amphibian_richness)

#first import all files in a single folder as a list 
path_a <- "../data/SpeciesProjections/SpeciesProjections/Future/mc85bi70/Amphibians/"
amphibians <- list.files(path = path_a, pattern='.tif$', all.files=TRUE, full.names=FALSE)

amphibian_richness <- raster(paste0(path_a, amphibians[1]))
for (i in 2:length(amphibians)) {
  spp <- raster(paste0(path_a, amphibians[i]))
  amphibians_stack <- stack(amphibian_richness, spp)
  amphibian_richness <- calc(amphibians_stack, sum)
}
amphibian_mc <- amphibian_richness
rm(amphibians_stack, spp, tree, path_a, amphibian_richness)
```

```{r}
amphibians <- stack(amphibian_mc, amphibian_in, amphibian_gf)
amphibians_future <- calc(amphibians, mean)
writeRaster(amphibians_future, "../data/richness_rasters/amphibians_future_lawler.tif")
```
