---
title: "MOBI-data"
output: html_document
---

```{r}
library(rstac)
library(terra)
library(tmap)
## Access the "mobi" collection:
it_obj <- stac("https://planetarycomputer.microsoft.com/api/stac/v1") %>%
  stac_search(collections = "mobi") %>%
  get_request() %>%
  items_sign(sign_fn = sign_planetary_computer()) # basically an API key for rate limiting purposes;

url <- paste0("/vsicurl/", it_obj$features[[1]]$assets$SpeciesRichness_Vertebrates$href)
data <- terra::rast(url) # look, no download! lazy read a remote connection. 

tm_shape(data) + tm_raster()
```

```{r}
## Search for data from a given collection in a given bounding box:
s_obj <- stac("https://planetarycomputer.microsoft.com/api/stac/v1/")

it_obj <- s_obj %>% 
  stac_search(collections = "landsat-8-c2-l2",
              bbox = c(-47.02148, -17.35063, -42.53906, -12.98314)) %>%
  get_request() %>%
  items_sign(sign_fn = sign_planetary_computer())


url <- paste0("/vsicurl/", it_obj$features[[1]]$assets$SR_B2$href)
data <- terra::rast(url) ## lazy-read ~ 100 MB file over the network, no disk storage
data
# plot(data)
tm_shape(data) + tm_raster()
```

```{r}
sf::st_read("/vsizip//vsicurl/https://raw.githubusercontent.com/OSGeo/gdal/master/autotest/ogr/data/shp/poly.zip") %>% plot()
```

```{r}
options(repos = c(
    hypertidy = 'https://hypertidy.r-universe.dev',
    CRAN = 'https://cloud.r-project.org'))

# Install some packages
install.packages(c('vapour', 'gdalio'))
```

```{r}
library(gdalio) ## 
u <- "WMS:https://tiles.maps.eox.at/?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&LAYERS=s2cloudless-2019&SRS=EPSG:4326&BBOX=-180.000000,-90.000000,180.000000,90.000000&FORMAT=image/png&TILESIZE=256&OVERVIEWCOUNT=17&MINRESOLUTION=0.0000053644180298&TILED=true"
gdalio_set_default_grid(list(extent = c(-1, 1, -1, 1) * 1e6, 
                             dimension = c(1024, 1024), 
                             projection = "+proj=laea +lon_0=139 +lat_0=39"))
x <- gdalio_graphics(u)
plot(x)
```

